### ISSUE TITLE
How can I convert ListHeaderComponent to sticky header?

### ISSUE THREAD

**Issue by bloggerklik** [Shopify/flash-list#1019]
I have a component in `ListHeaderComponent`. I want to convert this into a sticky header. How can I do it? In` FlatList`, it is sufficient to give `stickyHeaderIndices={[0]}`. But this does not work in `FlashList`.
```
            <FlatList
                stickyHeaderIndices={[0]}
                ListHeaderComponent={ <Header/> }
            />
```

**Comment by Randall71** [comment]
check this page of the doc as an inspiration : https://shopify.github.io/flash-list/docs/guides/section-list

**Comment by naqvitalha** [comment]
Just make it first item of the list instead. Not following FlatList here was intentional and we don't plan on changing that.

**Comment by mustafaabobakr** [comment]
# Why is this closed ?

<table>
 <tr>
  <th>Flatlist ✅ </th>
  <th>Flashlist ❌ </th>
 </tr>
 <tr>
  <td>

https://github.com/user-attachments/assets/b3f0abcf-c53d-4c65-9848-13427d6a3817

  </td>
  <td>

https://github.com/user-attachments/assets/e576720a-b836-4073-a21e-aed8729de9aa

  </td>
 </tr>
</table>

**Comment by jefferyjxn** [comment]
> [@naqvitalha](https://github.com/naqvitalha)
> 
> > Just make it first item of the list instead. Not following FlatList here was intentional and we don't plan on changing that.
> 
> How would this work exactly if numColumns is greater than 1? My ListHeaderComponent has the full width of the list and by making it the first item it's treated as if it should fit in a column...

@WillyRamirez I'm assuming you've moved on from this, but in case anyone else stumbles upon this issue: You can define `overrideItemLayout` and inside of it set `layout.span` to the value of `numColumns` only for your header item. I agree overall that the required approach is a little confusing, but that should do what you need.

Example:

```
const numColumns = 5

const overrideItemLayout = (layout, item, index) => {
// override header span
if (index === 0) layout.span = numColumns
}

return (
  <FlashList
  numColumns={numColumns}
  overrideItemLayout={overrideItemLayout}
  />
)
```

**Comment by Tranthanh98** [comment]
> # Why is this closed ?
> Flatlist ✅	Flashlist ❌
>  Flatlist.-.sticky.header.mp4 
>  Flashlist.-.BUG.sticky.header.not.working.mp4

I faced with this problem in 2026 and they don't fuckin care about the contributed issues

**Comment by mayvagio2016** [comment]
> > # Why is this closed ?
> > Flatlist ✅	Flashlist ❌
> > Flatlist.-.sticky.header.mp4
> > Flashlist.-.BUG.sticky.header.not.working.mp4
> 
> I faced with this problem in 2026 and they don't fuckin care about the contributed issues

This is not a priority issue.

**Comment by web-iou** [comment]
Override the value of stickyHeaderIndices in the scrollview using overrideProps [1]
But this usually only solves the problem of using the entire head for adhesion.
