### ISSUE TITLE
App crash on android with flash-list 1.6.3

### ISSUE THREAD

**Issue by wesleyvandevoorde** [Shopify/flash-list#1026]
## Current behavior

App crashes on Android after a couple of seconds while we use the latest version of flash-list 1.6.3, works fine on 1.6.1

![Uploading Image.jpeg…]()

## Expected behavior

App should works as expected without crashing

## To Reproduce

Our flashlist code: 

```
  <FlashList
        testID={`${testId}_section_list`}
        ref={ref}
        keyboardShouldPersistTaps={'handled'}
        data={data}
        renderItem={renderItem}
        onRefresh={onRefresh}
        refreshing={refreshing}
        getItemType={(item) => item.type}
        stickyHeaderIndices={stickyHeaderIndices}
        estimatedItemSize={100}
        ListFooterComponent={renderListFooter}
        onEndReached={onLoadMore}
        onEndReachedThreshold={0.5}
        contentContainerStyle={keyboardShownStyle}
        keyExtractor={(w) => w.key}
      />

```

## Platform:

- [ ] iOS
- [x] Android

## Environment

1.6.3

**Comment by herberthk** [comment]
I'm facing the same issue, @wesleyvandevoorde were you able to solve the issue?

**Comment by naqvitalha** [comment]
Closing due to lack of stacktrace.
