### ISSUE TITLE
Intermittent 'x' of undefined error in flashList using ranimated

### ISSUE THREAD

**Issue by devym-37** [Shopify/flash-list#1046]
## Current behavior
- I am intermittently getting 'x' of undefined errors with sentry errors.

<img width="525" alt="Screenshot 2024-02-06 at 9 42 05 AM" src="https://github.com/Shopify/flash-list/assets/25405849/bd669c6d-8bf0-42fe-bcaa-5c09d8617c30">

## Platform:

- [x] iOS
- [ ] Android

## Environment

@shopify/flash-list : 1.6.2
react-native: 0.71.15
react-native-reanimated: 2.14.4

x.y.z

**Comment by naqvitalha** [comment]
Please make sure you aren't mutating the data array passed to FlashList elsewhere.
