### ISSUE TITLE
Nested flashlist is not rendering properly, flickering issue on first render.

### ISSUE THREAD

**Issue by Sunil-Holcim** [Shopify/flash-list#1062]
Hi there!

I am facing some issue when using nested flashlist, it's not rendering properly list item overlapping on first render. It has some flickering issue.

## Current behavior

https://github.com/Shopify/flash-list/assets/133321716/abd52aa8-f596-4c33-b967-74fd4910dc73

## Expected behavior

https://github.com/Shopify/flash-list/assets/133321716/10cdb8af-aab6-41ad-b203-81b61445682f

## To Reproduce

Please check this repo to reproduce the issue. I have created a sample app. 
https://github.com/Sunil-Holcim/FlashlistApp

## Platform:

- [ ] iOS

## Environment

@shopify/flash-list@^1.6.3
react-native@0.73.4

**Comment by kanadgodse-lh** [comment]
Hi team, any update on this?

We are trying to replace FlatList with FlashList in our project but are facing this issue with nested FlashLists.

**Comment by felipejh** [comment]
It looks you need to use the Section List approach intead of nested lists.

Please take a look at this: https://shopify.github.io/flash-list/docs/guides/section-list
By following that you will have only one list (one array).

**Comment by naqvitalha** [comment]
FlashList isn't designed to be nested inside another FlashList of the same orientation. For you use case please follow what @felipejh mentioned.

**Comment by chanphiromsok** [comment]
> FlashList isn't designed to be nested inside another FlashList of the same orientation. For you use case please follow what @felipejh mentioned.

How about flipkart Home ? is this app using RecycleView or just FlatList >?
