### ISSUE TITLE
changing data after scrolling causes over-rendering and performance degradation

### ISSUE THREAD

**Issue by aweary** [Shopify/flash-list#1116]
## Current behavior

At @discord we use `FlashList` to render the channel list for each server. There are often a variable amount of channels in each server, ranging from 1 to 500 (the maximum). Users will often switch between servers frequently, which means that the `data` for the channel `FlashList` changes frequently. 

The issue I've noticed is that `data` changing _when a user has scrolled and rendered many rows_ results in a noticeably slower update. For example:

* Server `A` mounts with `120` channels
* Initial set of rows renders (say, `25` channels)
* The user scrolls to the bottom of the channel list
  * At this point [the `renderStack` of `recyclerlistview`](https://github.com/Flipkart/recyclerlistview/blob/master/src/core/RecyclerListView.tsx#L742-L749) has approximately `120` items in the stack
* The user switches to server `B` which also has `120` channels
* **`FlashList` then renders all `120` channels on the initial render of the new server** because the `renderStack` is still populated from server `A`'s data and there are roughly the same number of items in each server's respective `data` array.

This scenario causes a very noticeable performance degradation, especially on low-mid end Android devices.

## Expected behavior

Ideally, when `data` changes the `renderStack` size would be reset or limited so that its not over-rendering. Looking at https://github.com/Flipkart/recyclerlistview/blob/master/src/core/VirtualRenderer.ts#L258-L259 it seems like our use case where `data` changes somewhat frequently might be a pathologically bad case for `recyclerlistview` which we'd love to optimize more.

## To Reproduce

Will put something together soon, but should be trivial to repro changing `data` after scrolling

## Platform:

- [x] iOS
- [x] Android

## Environment

[1.6.3](https://www.npmjs.com/package/@shopify/flash-list/v/1.6.3)

**Comment by aweary** [comment]
>  if 25 is the initial count of items then it should not go upto 120 to fill its buffer. Seems very high
@naqvitalha as far as I can tell, the `renderStack` only increases in size as you scroll. Logging the length of `renderedItems` here https://github.com/Flipkart/recyclerlistview/blob/master/src/core/RecyclerListView.tsx#L750 I have never seen it decrease when scrolling a list, and I don't see where the mechanism that would reduce that buffer size would be?

**Comment by naqvitalha** [comment]
Yes you are right. `getItemType` usage can lead to an increase in the number of items in the pool. If certain elements are inexpensive to create then you can give them the same type and that will reduce the count. Giving the same type might lead to incorrect reuse and some mount/unmount but might be a good tradeoff in your use case.
