### ISSUE TITLE
Style Mismatches from Flatlist

### ISSUE THREAD

**Issue by spagrhetti** [Shopify/flash-list#1121]
## Current behavior

I am trying to display 3 columns of items. With the exact same styles, flashlist has different styles than flatlist, adding different margins between the items and a mystery 1px padding to the right of the flatlist, as shown in this snack and images:

FlatList:

<img width="453" alt="Screenshot 2024-03-29 at 9 30 32 AM" src="https://github.com/Shopify/flash-list/assets/139802043/18025bd9-8e88-44f3-b43d-76d93f19d8bc">

FlashList:

<img width="457" alt="Screenshot 2024-03-29 at 9 31 01 AM" src="https://github.com/Shopify/flash-list/assets/139802043/5f5b011d-273c-41af-a99f-e7b299c86b1f">

Snack with code:

https://snack.expo.dev/@spagrhetti/flashlist-background-image-header

Additionally, with this same demo, since FlashList doesn't accept a style prop, I'm unable to add padding to the top of the container so that I can have an image at the top of the screen that the items then scroll over (and have a background behind them), is there any way to recreate that style with FlashList?

Note: I can get rid of the extra padding by instead using DEVICE_WIDTH / 3 width items, then using padding instead of margins. That version is in the snack, commented out.

## Expected behavior

For the style to match flatlist.

## Platform:

- [x] iOS
- [ ] Android

## Environment

1.4.3

**Comment by naqvitalha** [comment]
FlashList handles columns in a different way and lacks a row wrapper. Each column has a precomputed width already, I created the following snack that you can refer to implement this the right way: https://snack.expo.dev/qM1gql0L7skUdtIDtp2Oh
