### ISSUE TITLE
MasonryFlashList Items Stacking to the Side on iOS - Looks Fine on Android

### ISSUE THREAD

**Issue by gtwilliams03** [Shopify/flash-list#1264]
## Current behavior

Running a "photo gallery" type screen using the Masonry layout in an expo managed app running flash-list 1.6.4 in react-native 0.73.4. In Android, the screen looks fine.  In iOS, the items are stacked and overlapping in the left-hand column. 

## Expected behavior

Should look like the Android photo below.

## To Reproduce

Happy to privately share a link to my app repo if that is helpful. 

## Platform:

- [X] iOS
- [ ] Android

## Environment

Using react-native 0.74.3 - NEW ARCHITECTURE ENABLED (this does not happen with the old architecture)
@shopify/flash-list 1.6.4

```
            <MasonryFlashList data={lightboxImages}
                numColumns={4}
                estimatedItemSize={_maxThumbnailHeight}
                contentContainerStyle={{
                    paddingHorizontal: 1,
                }}
                keyExtractor={(item, index) => `masonry-view-${item.key}`}
                renderItem={({ item, index }) => {
                    const i = item
                    return (
                        <Pressable onPress={() => showPhoto(index)}
                            disabled={i._id === deletingId} 
                            style={({ pressed }) => ({ ...(pressed ? { opacity: 0.5 } : {}) })}>
                            <View style={{ ...s.galleryImageContainer, ...(i._id === deletingId ? s.deletingImage : {}) }}>
                                <Image source={{ uri: i.galleryUrl }}                             
                                    PlaceholderContent={<ActivityIndicator />}
                                    resizeMethod='scale'
                                    resizeMode='cover'
                                    style={{ width: width / 4, height: (width / 4) / (i.aspectRatio || 1), aspectRatio: i.aspectRatio }} />
                            </View>
                        </Pressable>
                    )
                }} />

```

Looks like this on an Android device in production:

![Android Gallery - Looks Fine](https://github.com/Shopify/flash-list/assets/1564628/d45d89f4-4d3e-43a1-b669-7bb660ab49d2)

Looks like this in iOS:

![iOS Gallery - Masonry Problem](https://github.com/Shopify/flash-list/assets/1564628/e4c15d95-ae61-4547-9aca-345b329ad95d)

**Comment by gtwilliams03** [comment]
I do note that I am using 1.6.4 in a new architecture expo build, and I have opened an issue with expo to update flash-list to 1.7.0 which indicates that it works with new architecture. 

[https://github.com/expo/expo/issues/30329](https://github.com/expo/expo/issues/30329)

**Comment by hanwenbo** [comment]
![Image](https://github.com/user-attachments/assets/4d42d1c1-49cf-449b-b522-1de1de786c95)
@gtwilliams03 
 "@shopify/flash-list": "^1.7.1",  still

As the scroll increases more, it gets mixed up
