### ISSUE TITLE
Optimize Swipeable when used with FlashList

### ISSUE THREAD

**Issue by fortmarek** [Shopify/flash-list#366]
When benchmarking [Swipeable](https://github.com/Shopify/react-native-swipe-actions), we have found a [couple of issues](https://github.com/Shopify/flash-list/issues/198#issuecomment-1112309340) making the component slower than expected. We should strive for Swipeable causing max 5 % performance drop.

**Comment by hirbod** [comment]
@fortmarek where can I find this mysterious react-native-swipe-actions package? :)

**Comment by fortmarek** [comment]
> where can I find this mysterious react-native-swipe-actions package? :)

This is, for the time being, unfortunately an internal package

**Comment by erennyuksell** [comment]
@hirbod i tried with react-native-gesture-handler's Swipeable there is a dramatic drop in performance

**Comment by Acetyld** [comment]
Same problem here, massive performance drop while using swipeable from gesture-handle

**Comment by K-Leon** [comment]
Found anyone a solution?

**Comment by erennyuksell** [comment]
> > @hirbod i tried with react-native-gesture-handler's Swipeable there is a dramatic drop in performance
> 
> Did you memoize the Gesture object with useMemo? That's super important.

yes i memorized

**Comment by Acetyld** [comment]
Same here, any kind of memo no success
