### ISSUE TITLE
Add FlashList to shopify.github.io site

### ISSUE THREAD

**Issue by davebcn87** [Shopify/flash-list#440]
What
====
There is this website with list of open source projects. FlashList should be there once it's open. 

How
===
To be able to appear on that landing, we should add the repo name to this list. Use `react-native-skia` [PR](https://github.com/Shopify/shopify.github.com/pull/99/files) as a reference on what to do.

**Comment by fortmarek** [comment]
Added [here](https://github.com/Shopify/shopify.github.com/pull/107).
