### ISSUE TITLE
[Warning] FlashList's rendered size is not usable.

### ISSUE THREAD

**Issue by kayode0x** [Shopify/flash-list#483]
Hi there, so I tried migrating from Flatlist, a but I keep getting a warning:
```
FlashList's rendered size is not usable. Either the height or width is too small (<2px). 
Please make sure that the parent view of the list has a valid size. 
FlashList will match the size of the parent.
```
This is what my code looks like:
```
const FlashListView = ({ data }: IProps) => {
    const keyExtractor = (item: IBookmark) => item._id;
    return (
        <View style={{ flex: 1 }}>
            <FlashList
                data={data}
                estimatedItemSize={200}
                keyExtractor={keyExtractor}
                renderItem={({ item }) => (
                    <View style={{ height: 10, width: "100%" }}>
                          {item.name}
                    </View>
                )}
            />
        </View>
    );
};
```

I understand it's simply a warning, but I'm curious if I've been missing something or doing something wrong, thanks.

The project is on Expo SDK 45 (dev-client) & react-native: 0.68.2.

**Comment by ramiel1999** [comment]
I am just guessing here, but does the parent of FlashListView has a valid size?

**Comment by naqvitalha** [comment]
You can monitor onLayout on the list and see when it's raised as 0. Overall, this is expected if the list's size is incorrect.

**Comment by LouisMuriuki** [comment]
@kayode0x I have the same issue how did you fix this???

**Comment by LouisMuriuki** [comment]
> You can monitor onLayout on the list and see when it's raised as 0. Overall, this is expected if the list's size is incorrect.

what do you mean if list size is incorrect. I have  wrapped the flashlist with a view of flex:1

**Comment by kayode0x** [comment]
> @kayode0x I have the same issue how did you fix this???
> 
> 

Adding a getItemLayout prop fixed it for me.

```

const getItemLayout = (data: any, index: number) => ({
        length: 100,
        offset: index * 100,
        index,
    });

```

**Comment by LouisMuriuki** [comment]
This did not work for me,, warning is still persistant
Also in the doc they say this does not have any effect
But thanks

**Comment by DLevai94** [comment]
> You can monitor onLayout on the list and see when it's raised as 0. Overall, this is expected if the list's size is incorrect.

What would be a correct list size? Why `flex: 1` isn't ok to size the parent view? I think this warning is confusing.

**Comment by sebastienlabine** [comment]
Applying flexDirection: "row" in the styles fixed it for me

**Comment by megabeehothanhminh** [comment]
For someone need: 
 ```
estimatedItemSize={120}
estimatedListSize={{ height: 120, width: Dimensions.get("screen").width }}
```

**Comment by vikasis4** [comment]
i tried every solution in the replies but still getting the warning, any suggestion ?

**Comment by kayode0x** [comment]
> If someone can help me please, I am still facing that issue:
> 
> 
> 
> `import React from "react";
> 
> import { View, Text, Image, TouchableOpacity, Dimensions } from "react-native";
> 
> import data from "../../data.json";
> 
> import { FlashList } from "@shopify/flash-list";
> 
> import { AntDesign } from "@expo/vector-icons";
> 
> 
> 
> const Products = () => {
> 
>   const renderProduct = ({ item }) => (
> 
>     <View className="m-2 bg-white rounded-2xl overflow-hidden shadow">
> 
>       <View className="flex-row items-center">
> 
>         <Image
> 
>           source={{ uri: item.imageUrl }}
> 
>           className="w-24 h-24 rounded-2xl m-2"
> 
>           resizeMode="cover"
> 
>         />
> 
>         <View className="flex-grow p-4">
> 
>           <Text className="text-lg font-bold text-black">{`R$ ${item.price}`}</Text>
> 
>           <Text className="text-md text-black">{item.name}</Text>
> 
>         </View>
> 
>         <TouchableOpacity
> 
>           className="bg-orange-500 h-14 w-14 m-2 justify-center items-center rounded-full"
> 
>           // onPress={onAddToCart}
> 
>         >
> 
>           <AntDesign name="shoppingcart" size={25} color="white" />
> 
>         </TouchableOpacity>
> 
>       </View>
> 
>     </View>
> 
>   );
> 
> 
> 
>   return (
> 
>     <View style={{ height: Dimensions.get("screen").height }}>
> 
>       {data && data.length > 0 && (
> 
>         <FlashList
> 
>           data={data}
> 
>           renderItem={renderProduct}
> 
>           keyExtractor={(item) => item.id.toString()}
> 
>           showsVerticalScrollIndicator={true}
> 
>         />
> 
>       )}
> 
>     </View>
> 
>   );
> 
> };
> 
> 
> 
> export default Products;
> 
> `

try adding the estimated list and item sizes. [here's an example](https://github.com/Shopify/flash-list/issues/483#issuecomment-1620947519)

**Comment by Nicolas123-coder** [comment]
I tried and still getting the error :(

**Comment by chatwick** [comment]
> For someone need:
> 
> ```
> estimatedItemSize={120}
> estimatedListSize={{ height: 120, width: Dimensions.get("screen").width }}
> ```

Giving a fixed size to the parent container and adding the estimatedListSize fixed the issue for me.

**Comment by thrueweather** [comment]
Hey guys could you help me, please? I'm getting this warning when opening a new screen from the general stack. I tried to put height to the parent container and still getting this error 

Here`s my code 

```
<Stack.Navigator screenOptions={screenOptions}>
            <Stack.Screen name='Chats' component={ChatList} />
            <Stack.Screen name='Chat' component={Messages} />
            <Stack.Screen name='Profile' component={Profile} initialParams={{ isChatScreen: true }} /> (warning)
            <Stack.Screen name='Shared Media' component={SharedMedia} /> (warning)
 </Stack.Navigator>
```


```
<FlashList
    inverted
    ref={listRef}
    data={allMessages}
    keyExtractor={(item) => item.id}
    renderItem={renderItem}
    estimatedItemSize={120}
    onEndReachedThreshold={0.1}
    onEndReached={onEndReached}
    extraData={selectedMessages}
/>;
```

**Comment by badalsaibo** [comment]
@thrueweather Can you provide a gist to your Profile component?

**Comment by thrueweather** [comment]
> @thrueweather Can you provide a gist to your Profile component?

I don't think it`s a problem with the Profile component or ShareMedia. The warning appears immediately after I redirect to another screen

I'm getting warning even with an empty component

**Comment by arditderstila** [comment]
The warning appears immediately after I redirect to another screen  For me too

**Comment by Ozaoujal** [comment]
I have the same issue, in mind I have very large list with width of more than 1000%
