### ISSUE TITLE
contentContainerStyle retro-compatibility ?

### ISSUE THREAD

**Issue by billouboq** [Shopify/flash-list#491]
Hello !

Thank you first for this package, I'm really thrilled to use it !

I tried to migrate from FlatList to FlashList and found that my paddingHorizontal is not working when passed to contentContainerStyle props. Is there something to do to add paddings to the list ?

**Comment by ammarahm-ed** [comment]
@billouboq Add padding to the wrapper View component.

```jsx

<View style={{ paddingHorizontal:12 }} >
<FlashList/>
</View
```

**Comment by billouboq** [comment]
Yep already created some container around FlashLists but I wanted to know if it will be possible in the future to use styles props the same way in FlatList and FlashList or if we need to think differently when using FlashList and it will stay that way ?

**Comment by billouboq** [comment]
Thanks for the reply ! And thank you for the hard work !

Le sam. 2 juil. 2022 à 15:33, Talha Naqvi ***@***.***> a
écrit :

**Comment by hyochan** [comment]
> @billouboq Add padding to the wrapper View component.
> 
> ```js
> <View style={{ paddingHorizontal:12 }} >
> <FlashList/>
> </View
> ```

I think this isn't a good solution. 
<img width="465" alt="Screen Shot 2022-08-04 at 10 57 04 AM" src="https://user-images.githubusercontent.com/27461460/182746592-99dcd03a-5919-4f6b-9c5e-4538ef8892f7.png">

You will see a vertical scroll indicator also padded which is not expected.

**Comment by billouboq** [comment]
Put padding on your items not the list wrapper
