### ISSUE TITLE
Build fails on Android with error "No signature of method: org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.kotlinVersion() is applicable for argument types: () values: []"

### ISSUE THREAD

**Issue by micheleb** [Shopify/flash-list#495]
Hi there 👋🏻 and thanks for the great library!

I'm getting the error reported in the title when building my RN app on Android, which is due to line 18 in flash-list's `build.gradle`:

```
    ext._kotlinVersion = rootProject.ext.has("kotlinVersion") ?  rootProject.ext.kotlinVersion() : '1.5.30'
```

I already had a `kotlinVersion` variable defined in my project, like this:

```
buildscript {
    ext {
        // ... many other variables, and then
        kotlinVersion = "1.6.10"
```

so that `rootProject.ext.kotlinVersion()` is invoking my string variable as a function, which is causing the issue.

Removing the `kotlinVersion` variable declaration from my `build.gradle` fixes the issue, but I was wondering if it's more common to have that variable defined as a function? I thought my setup was pretty standard there 🤷🏻 

Thanks!

**Comment by AndreiCalazans** [comment]
@brentvatne it seems like [your recent change](https://github.com/Shopify/flash-list/pull/481) is causing this issue for those of us that set the kotlinVersion. Question, is there a better way to set the kotlinVersion to make it compatible with your change? 

```
buildscript {
    ext {
...
        kotlinVersion = '1.6.10'
   ... 
} 
```

**Comment by AndreiCalazans** [comment]
This pattern of reading `ext.kotlinVersion()` seems to only be used by Expo projects - [see Github search](https://cs.github.com/?q=ext.kotlinVersion%28%29&p=1&pt=5e0c4b5c735d309c58cc50eabac86df91fe33a16c33c044262cff154c76aea9e1857ae0541ed18dfe70565bd0843871c1728f5fd4a68262de77d09b42e8428033c0a8db76a832bf62d5d3dde2f15c93d7e219bf94b21dd0c7a0c367e0bc67249c74d15687a8bc5896f6754b40dc85dc38df78a65662da44c4dcced6923ee10d52fe55d558fa7ac6282ce457ec1ee3ea7c8e7cb5834006fba7dea21be8da819144a774492e095b3d1c416f47a74f680dd12ef3800982df7f6b69c4e2fec19dafd3426c09d095512142873ef64cd143cabd3a0ea5c46ae50d430040d23768644eae272fa6aea12dbe537cd93b80627f6479fb53f1e20b062cd1b9f45c034e83b3d9800a1303cc92b5f711f1559d1f33ca4d0be5da16346e65ef70bad40ce9bb2299b49feaf6a25e3aca3d4ba2c62f4a5bde38603058877ed4c0b2c0846acbd94c9ffa31feea782913ef6220e1ae214dd629aeb70eb673e63593fab4078e144ff2ffafe0992d6d56172a8e1683537f9d4806a77b5006c3b3ed31825a24d5eb121aad69321635961144651f58eadf36bfad9&scope=&scopeName=All+repos)


The fix should be to do what they do:
```
  // Ensures backward compatibility
  ext.getKotlinVersion = {
    if (ext.has("kotlinVersion")) {
      ext.kotlinVersion()
    } else {
      ext.safeExtGet("kotlinVersion", "1.5.30")
    }
  }
  ```

**Comment by naqvitalha** [comment]
@AndreiCalazans I've already fixed this in main. Got other reports of this as well.
@micheleb Use 1.0.2 to avoid the error. We will push a new version with the fix next week.

**Comment by EmmanuelVegher** [comment]
A problem occurred evaluating project ':tflite'. > No signature of method: build_dhynuayzew12ns5sg55k4fsn7.android() is applicable for argument types: (build_dhynuayzew12ns5sg55k4fsn7$_run_closure2) values: [build_dhynuayzew12ns5sg55k4fsn7$_run_closure2@3553ed87]


Im faced with the above stated problem

**Comment by rsbindmzp** [comment]
A problem occurred evaluating project ':app'.
> No signature of method: build_61blo3p6sbxqvk5q9fs1ko34n.android() is applicable for argument types: (build_61blo3p6sbxqvk5q9fs1ko34n$_run_closure2) values: [build_61blo3p6sbxqvk5q9fs1ko34n$_run_closure2@208a4fb]



I am also getting this error. please help me to solve this

**Comment by UgurGumushan** [comment]
_Not Shopify related, but_
I resolved it by using 
`buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", "false"`
instead of
`buildConfigField "boolean", "IS_NEW_ARCHITECTURE_ENABLED", isNewArchitectureEnabled().toString()`
on my app/build.gradle file
_You may be using a function which is not available_

**Comment by waqadArshad** [comment]
ok. it says that there is a problem in your app/build.gradle  so I copied another project's app/build.gradle ad up it in mine and changed the applicationId accordingly and that  worked. Maye that helps you too.
