### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by louisholley** [Shopify/flash-list#509]
## Current behavior

dropping in FlashList in place of a FlatList in our React Native Web project gives the error `SyntaxError: Cannot use import statement outside a module`

## Expected behavior

no error

## To Reproduce

not sure if it's anything specific to do with our setup as the docs seem to suggest it should work on web?

## Platform:

- [ ] iOS
- [ ] Android
- [x] Web

## Environment

1.0.4

**Comment by louisholley** [comment]
when running on iOS (managed expo) we get `Invariant Violation: requireNativeComponent: "AutoLayoutView" was not found in the UIManager.` 😕

**Comment by dhatGuy** [comment]
Use expo-dev-client

**Comment by louisholley** [comment]
@dhatGuy so it can't be used with react native web currently?

**Comment by louisholley** [comment]
@dhatGuy i'm getting the error in question on react native web also

**Comment by dhatGuy** [comment]
I ran this [demo](https://github.com/EvanBacon/Expo-Flash-List-Demo) and the web version worked. Maybe there's a configuration needed for solito. I'm not quite sure.

**Comment by louisholley** [comment]
ahh i think it's a nextjs issue, will try to transpile the module...

**Comment by louisholley** [comment]
yeah, works with `next-transpile-modules`!

**Comment by dhatGuy** [comment]
can I see the config? I tried it adding flashlist to next-transpile-modules, still getting the error

**Comment by pleaseshutup** [comment]
> eah, work

Can you share your next.config.js file ?

**Comment by pleaseshutup** [comment]
> yeah, works with `next-transpile-modules`!

@louisholley can you share your next.config.js ?

**Comment by pleaseshutup** [comment]
FYI for me this was the list to include with nextjs next-transpile-modules to get flashlist to work with nextjs

`const withTM = require('next-transpile-modules')(['react-native-web', '@shopify/flash-list', 'recyclerlistview'])`
