### ISSUE TITLE
`inverted` prop flips horizontal lists vertically instead of horizontally

### ISSUE THREAD

**Issue by mmmoussa** [Shopify/flash-list#512]
## Current behavior

Setting the `inverted` prop to `true` on a horizontal list inverts the list vertically instead of horizontally.

## Expected behavior

The list should be inverted horizontally.

## To Reproduce

Render a horizontal list of items containing text and set `inverted` to true.

## Platform:

- [X] iOS
- [X] Android

## Environment

1.0.4

**Comment by naqvitalha** [comment]
What is a real world use case for an inverted horizontal list? We actually plan on throwing an exception of the list is used this way.
I'd love to understand why we should support this

**Comment by mmmoussa** [comment]
Rendering books. Books have a directionality that is independent of device locale. For example, when rendering an English book, you can render each page as an item in a horizontal list, going from left to right. If the app is in an rtl locale, the pages should still go from left to right and hence you need the `inverted` prop. Similarly, in the case of a book from an rtl language, you may want to always render the list of pages from right to left and hence need to use the `inverted` prop when the app is using a ltr locale.

More broadly, I can imagine there are many use cases where leveraging the `inverted` prop in combination with app locale directionality woud be important, let alone the case I mentioned above where the content directionality is a factor as well.
