### ISSUE TITLE
recycled views also recycle prior useState values

### ISSUE THREAD

**Issue by sterlingwes** [Shopify/flash-list#527]
## Current behavior

Cell components with a `useState` are rendering the state of prior cells, presumably due to the memory cache or previously mounted component reuse (?)

See this repro in the Twitter Timeline fixture app where a "like" of the first tweet shows up on a later tweet:

https://user-images.githubusercontent.com/1047502/178994225-09157b84-ae22-41c5-8e62-b2adae0aa17b.mp4

## Expected behavior

Prior useState values should not affect recycled cells

## To Reproduce

See code: https://github.com/sterlingwes/flash-list/compare/main...sterlingwes:flash-list:usestate-bug-repro

## Platform:

- [x] iOS
- [x] Android

## Environment

1.1.0

**Comment by sterlingwes** [comment]
There's two workarounds for this I figure:
1. don't use `useState`s in anything returned by `renderItem` (probably a good performance idea but kind of unreasonable if the sales pitch is "drop-in replacement for FlatList")
2. add a useEffect to reset any state:

```jsx
const MyRecycledComponent = (props) => {
  const lastKey = useRef(props.myItemKey)
  const [myState, setMyState] = useState(props.myInitialState)
  useEffect(() => {
    if (props.myItemKey !== lastKey.current) {
      lastKey.current = props.myItemKey
      setMyState(props.myInitialState)
    }
  }, [props])
  return <View><Text>{myState}</Text></View>
}
```

If these sound like reasonable suggestions I can open a PR to add to Known Issues in the docs LMK

**Comment by huduarte** [comment]
> 

sorry ;D in my case, extraData works fine

**Comment by huduarte** [comment]
I'd like to re-render only the item I've selected, but since that doesn't work for me, I'm re-rendering the entire list. Maybe it really is a different usecase or else I'm screwing up

**Comment by naqvitalha** [comment]
@sterlingwes The useEffect solution will lead to two updates per render. Isn't ideal as it might cut down JS FPS. I think you can just setState during render like mentioned here: https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops

I don't really think it's an issue. It can also happen if you update FlatList data without having stable keys. A component should, ideally, always handle updates.

Instead of known issues, we should add this to the common pitfalls list under usage.

**Comment by fortmarek** [comment]
> I expected the native view representation to be recycled not the react component itself, but maybe I didn't read the docs well enough.

Not recycling the React component would also lead to a performance drop (creating a React component from scratch is not for free).

**Comment by sterlingwes** [comment]
> creating a React component from scratch is not for free

Nearly everything has a cost! I'm not new, it's just an unintuitive behaviour that I'm surprised is so expected given the likely prevalence of such primitives like `useState`. I imagine it's pretty intuitive to most people that when a view, backed by a component, appears on the screen, its first render is a mount not a render for an entirely different entity.

Thank you for explaining the expected behaviour to me in any case - I definitely think this should be documented. I'll update my PR and you can use it if you wish.

**Comment by sterlingwes** [comment]
(I'm sorry for the snark that was inappropriate)

Just know that I'm trying to help future devs when inevitably they run into this issue swapping from FlatList - I'm not trying to question your design decisions since ultimately they're what make this an improvement over FlatList.

Just please consider common expectations react devs might have before diminishing this issue

**Comment by naqvitalha** [comment]
@sterlingwes No worries, we're very glad that you've shared this feedback. It's super useful and I agree that it should be included in the docs.

**Comment by sterlingwes** [comment]
> We have the same problem. Not a big issue (tho not ideal) when starting a green field. But in our case we have over 200 FlatList and going 1-by-1 and manually reviewing if the `renderItem` is state-full or not... Well, it's not really what I had in mind when I read the "drop-in replacement for FlatList".
> 
> If at least, FlashList could throw a warn or something. Identify automatically those pesky `renderItems`. For now, we're skipping 😢

@sospedra how would you suggest that FlashList inspect state usage? That seems very out of scope since those are slots React manages

Also if you're going to thumbs-down a workaround suggestion maybe come suggest your own approach instead?

**Comment by naqvitalha** [comment]
@sospedra You should adopt it incrementally. Do a few of them first. 
FlashList is a drop in replacement in a lot of cases but there will be exceptions.

The user experience improvement will be worth it.
