### ISSUE TITLE
Changing minimumViewTime of viewabilityConfig prop does not warn developer of the inability to change on the fly

### ISSUE THREAD

**Issue by itsramiel** [Shopify/flash-list#530]
## Current behavior

Changing minimumViewTime of viewabilityConfig prop does not show a warning that it cant be changed on the fly. It was confusing for me because I didnt see a change in the behavior of the list till I mounted and unmounted the list.

## Expected behavior

Show a warning in the console and/or note in docs about not being able to change it on the fly for better DX

## To Reproduce

Render a list, change minimumViewTime, observe no changes/warning

## Platform:

- [x] iOS
- [x] Android

## Environment

1.1.0

**Comment by fortmarek** [comment]
Closing as duplicate of https://github.com/Shopify/flash-list/issues/637
