### ISSUE TITLE
RenderError (`null is not an object`) when using `estimatedListSize` and no data

### ISSUE THREAD

**Issue by renchap** [Shopify/flash-list#543]
## Current behavior

When using `estimatedListSize` with empty data, this error occurs:

```
This error is located at:
    in ProgressiveListView (created by StickyContainer)
    in RCTView (at View.js:32)
    in View (created by StickyContainer)
    in StickyContainer (created by FlashList)
    in FlashList (at List.tsx:65)
```

## Expected behavior

The app displays an empty list

## To Reproduce

Commit based on the fixture app reproducing the issue: https://github.com/renchap/flash-list/commit/1d179d6d8a1663d22a1584ba62c07fda36da4dd4

## Platform:

- [x] iOS
- [x] Android

## Environment

1.2.0

**Comment by Pickleboyonline** [comment]
I believe this error originated from the `recyclerlistview` that this repo depends on. Check out lines 206-216 in `RecyclerListView.tsx` in the `recyclerlistview` npm module.
