### ISSUE TITLE
v strange layout on web when item size deviates significantly

### ISSUE THREAD

**Issue by louisholley** [Shopify/flash-list#559]
## Current behavior

using a SectionList style implementation of a chat app, following the [guide](https://shopify.github.io/flash-list/docs/guides/section-list) in the FlashList docs. works great on iOS, but the layout is all over the place on web - there's a huge gap between items and some items are even rendering on top of each other

## Expected behavior

chat FlashList on iOS:
![simulator_screenshot_23229624-3C1E-4114-9339-716CDE36AA55](https://user-images.githubusercontent.com/4563781/184332521-a5466b22-2e03-4761-9eea-1596b45a05d7.png)

chat FlashList on web:
<img width="788" alt="Screenshot 2022-08-12 at 11 05 04" src="https://user-images.githubusercontent.com/4563781/184332610-26513aca-6678-4da9-b64f-7142be02ed82.png">
(here the Aug 5, 2022 is before the message with an image in the data list, but it's being rendered after/on top of the message)

## To Reproduce

will try to work on a repro today but wanted to get the issue posted in case anyone has experienced something similar or can offer advice

## Platform:

- [ ] iOS
- [ ] Android
- [x] Web

## Environment

1.2.1

**Comment by naqvitalha** [comment]
A repro will definitely help in debugging. Does this issue happen after scrolling or mount?

**Comment by louisholley** [comment]
it's currently happening after mount. in trying to create a simplified repro the behaviour seems fine on web even with a big variance in item sizes, so it could be something else we're doing that flashlist isn't happy with...will keep digging and open another issue if I get any closer to figuring out what's up!
