### ISSUE TITLE
Crash on android 12

### ISSUE THREAD

**Issue by namnguyen211** [Shopify/flash-list#572]
## Platform:

- [ ] iOS
- [x] Android

## Environment

^1.2.1

**Comment by fortmarek** [comment]
Hey, we'll need more information, closing until such information is provided.

**Comment by namnguyen211** [comment]
i updated issue

**Comment by fortmarek** [comment]
Unfortunately, we can't reproduce an issue like this. Please, provide a reproducible sample with steps.
