### ISSUE TITLE
Selecting items in list via longpress doesn't work after switching from FlatList to FlashList

### ISSUE THREAD

**Issue by Slapbox** [Shopify/flash-list#585]
## Current behavior

Long-pressing to initiate a multi-selection fails to trigger any update in the rendered items, although it does work with `FlatList`.

All other behaviors appear correct after the transition, except this issue.

**`FlashList` behavior:**
Note that selected items are not styled - and a non-long-press fails to add items to our accumulator and instead opens the item, because the rendered items are no longer aware there's a multi-selection occurring because they're not updating

![image](https://user-images.githubusercontent.com/6835891/188758510-778b633c-846c-4ad7-959f-17a9372e611b.png)

## Expected behavior

Code pattern that worked with `FlatList` should work with `FlashList` except where otherwise specified in the docs (which this doesn't appear to be)

**`FlatList` behavior:**
Long-pressing an item starts accumulating items in the list, and after the initial long press, a normal press on additional items will select them
![image](https://user-images.githubusercontent.com/6835891/188758433-67f605fe-6819-45cc-a0b8-38cb09452069.png)

## To Reproduce

TBD. `FlashList` is cool but I likely cannot justify the time to produce a repro given the minimal benefits it has in our use case.

## Platform:

- [ ] iOS
- [x] Android

## Environment

`1.1.0` and `1.2.2`

Note: We're using Expo and `1.2.2` isn't officially supported by it yet, so maybe it could influence my findings - but the issue definitely affects `1.1.0`

x.y.z

PS: This link in the issue template appears not to lead anywhere anymore: https://discord.com/channels/928252803867107358/986654488326701116

**Comment by Slapbox** [comment]
Friendly bump. I assume list children should be updatable like with FlatList? Can anyone confirm that?

**Comment by naqvitalha** [comment]
@Slapbox Make sure you update your extraData to force an update. FlashList only updates its children if `data` AND `renderItem` props change. The other option is to use extraData which should work for you.

**Comment by Slapbox** [comment]
It works; thanks for the tip!

I wonder if I just overlooked some warning about that in the docs? I noticed some mentions about height requirements and other small differences from `FlatList`, but I didn't see that mentioned.
