### ISSUE TITLE
contentContainerStyle doesn't accept array of objects.

### ISSUE THREAD

**Issue by zagoorland** [Shopify/flash-list#592]
I noticed a difference between types in contentContainerStyle in built-in RN Flatlist and FlashList.
Flatlist uses:
```tsx
StyleProp<ViewStyle>
```
And the FlashList uses its own `ContentStyle` type.
That breaks the ability to add array of objects in this props.

I'm using Expo 46 with FlashList 1.1 since it's latest compatible version.

**Comment by naqvitalha** [comment]
This is by design. We only support backgroundColor and padding props. You need to set them individually.
