### ISSUE TITLE
numColumns does not work correctly when autoLayout is enabled

### ISSUE THREAD

**Issue by omidshafai** [Shopify/flash-list#599]
## Current behavior
When I use the numColumns property, the layout gets messed up. But this problem is solved by setting the disableAutoLayout property to true.

In the image below, the value of numColumns is set to 3 and the value of disableAutoLayout is false:
<img src="https://user-images.githubusercontent.com/40908579/190085893-e956fbbe-c2cd-4221-b45f-5da8bec2f570.jpg" width="250px">

In the image below, the value of numColumns is set to 3 and the value of disableAutoLayout is true:
<img src="https://user-images.githubusercontent.com/40908579/190088631-89d3f287-4336-4f26-a310-beff3edf4890.jpg" width="250px">

## Platform:

- [ ] iOS
- [x] Android

## Environment

"@shopify/flash-list": "1.2.2"
"react-native": "0.66.4"

**Comment by naqvitalha** [comment]
I don't really understand the issue here. I lack the context as to why you'd want things to look a certain way. 
An expo sample will also be super useful .

**Comment by omidshafai** [comment]
It seems to work properly in the expo online tool:
https://snack.expo.dev/@omidshafaiy/72eadb?platform=android

But it has problems in the bare react native cli project version 0.66.4.

**Comment by naqvitalha** [comment]
The two should be identical. Can you help me understand the issue? I don't understand the issue honestly.

**Comment by fortmarek** [comment]
Please, create a new issue with reproduction steps if you are still experiencing a bug in the library.
