### ISSUE TITLE
[bug][ios]: using getItemType causes blanks and overlapping items

### ISSUE THREAD

**Issue by hirbod** [Shopify/flash-list#600]
## Current behavior
Using `getItemType` causes blanks and overlapping items.

I reproduced a bug where using getItemType causes blanks and overlapping items. This does only happen when using different types but the elements having the same height. In my Expo Snack, just using two types (e.g "header" and "row" does not break), since header and row have different heights. But I used different types (in my real app) because the items have different icons and styling, so I tried to add more types in order to optimize renders. While I could just use two types to "fix" this issue, getItemType should never cause this blanks, even when the items have the same height.

https://user-images.githubusercontent.com/504909/190257015-3e38ea4e-09d1-47b4-a6b1-4b246881a0e2.mp4

<img width="418" alt="Bildschirmfoto_2022-09-14_um_21 54 43" src="https://user-images.githubusercontent.com/504909/190257112-096ca6b1-95bd-46c6-b65a-fb121541c535.png">

I was only able to reproduce this on iOS, but honestly haven't tried android enough. It is not breaking on web.

## Expected behavior

Should not cause blanks and overlapping items

## To Reproduce

https://snack.expo.dev/@hirbod/getitemtype-failing

## Platform:

- [X] iOS
- [ ] Android

## Environment

Happens on iOS (bare react-native and expo, 1.1.0 and 1.2.1)

**Comment by naqvitalha** [comment]
@hirbod I looked into this and it seems like `getItemType` is returning a random value in the sample. Are you able to reproduce if you don't return something random?

**Comment by hirbod** [comment]
@naqvitalha yes, I am able to reproduce this. The random value was only for demonstration. It also happens when I just have 2 different types. (like in my app)

It does not happen when both types have different dimensions, only when you have different types with same item dimensions - at least thats my guess.

**Comment by hirbod** [comment]
@naqvitalha we had reports in the Discord group that this issue can even randomly occur even without the use of getItemType. So it just might be a coincidence or there is a general issue that can happen

**Comment by BalogunofAfrica** [comment]
Hi @hirbod what did you do to fix this? Currently experiencing this in our app

**Comment by singhayush1403** [comment]
Is this fixed? Still happening with me on version 1.6.1
