### ISSUE TITLE
wrong default value for animated in scrollToOffset

### ISSUE THREAD

**Issue by andresribeiro** [Shopify/flash-list#601]
## Current behavior

`animated` param in `scrollToOffset` seems to default to false, whereas docs indicates to be `true `

`"Param animated (true by default) defines whether the list should do an animation while scrolling."`

## Expected behavior

`animated` should be true by default

## To Reproduce

Just create a list, go to bottom and then call `scrollToOffset({ offset: 0 })` without passing a param to `animated`

## Platform:

- [ ] iOS (not tested on iOS)
- [x] Android

## Environment

`"@shopify/flash-list": "^1.2.2",`

**Comment by naqvitalha** [comment]
Yeah, we unfortunately used the wrong default value. Since it's going to be a breaking change at this point we'll keep it as it is. Docs will be updated soon.
