### ISSUE TITLE
undefined is not an object (evaluating 'itemRect.y')

### ISSUE THREAD

**Issue by khayym** [Shopify/flash-list#605]
I use FlatList component on different screens and if one screen is empty when cange numColums and renderItem component return "undefined is not an object (evaluating 'itemRect.y')" error. 
This happens if the content is empty on one screen.

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-09-17 at 01 55 35](https://user-images.githubusercontent.com/68564696/190810986-e0b285db-e445-4d36-8081-0bbe78df1211.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-09-17 at 02 05 16](https://user-images.githubusercontent.com/68564696/190810860-2b8ca853-5c94-4e19-9b5d-e94b623b4dce.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-09-15 at 11 29 49](https://user-images.githubusercontent.com/68564696/190811099-6c15b67f-c4ad-4b23-a08c-6a1cf6c32083.png)

#code 
`
export const ViewItems = ({ content, setContent }) => {
  //mode ture -> column, mode false -> row 
  const contentSetter = (con) => setContent(con);
  const { mode } = useSelector(state => state.files);
  return (
    <View style={styles.container}>
      <ViewItemHeader contentSetter={contentSetter} content={content?.length} />
      <FlashList
        data={content}
        disableAutoLayout={true}
        keyExtractor={(item, index) => item.path}
        extraData={mode}
        horizontal={false}
        ListEmptyComponent={<EmptyComponent />}
        showsVerticalScrollIndicator={false}
        numColumns={mode ? 1 : 3}
        renderItem={({ item }) => mode ? <Column item={item} contentSetter={contentSetter} /> : <Row item={item} contentSetter={contentSetter} />}
        estimatedItemSize={100}
      />
    </View>
  )
}
`
<img width="1440" alt="Screen Shot 2022-09-17 at 2 13 48 AM" src="https://user-images.githubusercontent.com/68564696/190814091-295e980e-e701-474d-a4e4-4b25c17d10e1.png">

## Platform:

- [ ] iOS
- [ ] Android

## Environment

@shopify/flash-list@1.2.2

**Comment by naqvitalha** [comment]
Do you mean that the issue happens if you change numColumns for an empty list?
I'm not sure if I fully understood the problem.

**Comment by fortmarek** [comment]
Closing. If the issues persists, you can open a new issue with full reproduction steps that we can look into.

**Comment by tmiyasa** [comment]
It is reproducible in the latest version. created a new issue.
https://github.com/Shopify/flash-list/issues/917
