### ISSUE TITLE
App crash when binding keyExtractor

### ISSUE THREAD

**Issue by HuuNguyen312** [Shopify/flash-list#622]
## Current behavior
I tried converting Flatlist to Flashlist

``` js
          <FlashList
            data={messages}
            estimatedItemSize={normalize(80)}
            renderItem={renderItemMessage}
            ref={scrollViewRef}
            inverted
            keyExtractor={(message) => message._id.toString()}
          />
```

The first time, it works fine.
But the crash happens after I add a message to messages.
With Flatlist,  the crash doesn't happen

https://user-images.githubusercontent.com/9895294/193225856-cdc50fd2-b535-45a2-ac17-387a437984a0.mov

<img width="449" alt="image" src="https://user-images.githubusercontent.com/9895294/193221351-3e242296-6bf4-40c0-b6a7-4299201b68b0.png">

## Platform:

- [ ] iOS

## Environment

1.3.0

**Comment by Slapbox** [comment]
I followed the steps for moving from using SectionList to FlashList: https://shopify.github.io/flash-list/docs/guides/section-list

But now our keyExtractor seems to cause crashes at this point due to `toString()`

`TypeError: Cannot read property 'toString' of undefined`

```js
getStableId = function (index) {
                // We assume `keyExtractor` function will never change from being `null | undefined` to defined and vice versa.
                // Similarly, data should never be `null | undefined` when `getStableId` is called.
                return flashList.props.keyExtractor(flashList.props.data[index], index).toString();
            };
```
