### ISSUE TITLE
The `stickyHeaderIndices` prop does not affect the ListHeaderComponent

### ISSUE THREAD

**Issue by justinjoyn** [Shopify/flash-list#624]
## Current behavior

I have provided a `ListHeaderComponent` and `stickyHeaderIndices={[0]}` on my `FlashList. This sticks the first item in the list instead of the  `ListHeaderComponent`

## Expected behavior

`ListHeaderComponent` should become sticky with `stickyHeaderIndices={[0]}`  prop

## To Reproduce

Create a FlashList with `ListHeaderComponent` and `stickyHeaderIndices={[0]}` and try scrolling.

## Platform:

- [x] iOS
- [x] Android

## Environment

1.3.0

**Comment by ethan-park-is** [comment]
same with https://github.com/Shopify/flash-list/issues/484

being said that 'this is by design', I think it seems very weird to me why List"Header"Component can't be sticky"Header" .

**Comment by TaiwoO** [comment]
Had to spin up a custom Sticky Header, works pretty well for me so far. Here's what I did:
1) Setup some variables. Change 135 to the height of your sticky
```js
  const scrollY = useRef(new Animated.Value(0));
  const scrollDiffClamp = useRef(
    Animated.diffClamp(filterScrollY.current, 0, 135)
  );
  const translateY = useRef(
    scrollDiffClamp.current.interpolate({
      inputRange: [0, 135],
      outputRange: [0, -135],
    })
  ).current;
```
2) Place your Header in an Animated View above the Flash list
```js
      <Animated.View
        style={{
          transform: [{ translateY: translateY }],
          zIndex: 1,
        }}
      >
        <MyHeader
          style={{ position: "absolute" }}
        />
      </Animated.View>
```

3) Finally add this onScroll handler to the Flash list. ITEM_HEIGHT is the height of the items in your Flash list
```js
 onScroll={(e) => {
              const yOffset = e.nativeEvent.contentOffset.y;
              const itemsScrolledPast = yOffset / ITEM_HEIGHT;

              // Prevents negative overscroll
              if (itemsScrolledPast <= 0) scrollY.current.setValue(0);
              else scrollY.current.setValue(yOffset);
            }}
```

**Comment by VictorioMolina** [comment]
Same here.

**Comment by megabeehothanhminh** [comment]
same

**Comment by JCcastagne** [comment]
So, still not update on this issue?

**Comment by naqvitalha** [comment]
Our logic was the `stickyHeaderIndices={[0]}` should point to first element in the data array regardless of whether header is present or not. You can easily make the header the first item in your list to get it to stick.

**Comment by maksim-romanov** [comment]
same problem for me ...
