### ISSUE TITLE
MasonryFlashlist second column disapppears after list data is updated

### ISSUE THREAD

**Issue by Wei102193** [Shopify/flash-list#627]
## Current behavior

https://user-images.githubusercontent.com/27971322/194217773-355bc7a4-a647-45ef-b239-bc951bf035fd.mp4

So I have a masonry list of menu items, which is updated when the menu category is changed. As shown in this video, after changed to a category that has only one column of data, and went back to the previous one, the second column on the previous one went missing. No issue with Flashlist.

## Platform:

- [x] iOS
- [x] Android

## Environment

1.3.0

**Comment by naqvitalha** [comment]
Can you please provide a sample where this can be reproduced so we can take a look?

**Comment by mlecoq** [comment]
I have a similar issue with a list where I can change the number of columns, going for 2 to 1 column than from 1 to 2, I have a part of my list displayed on 1 column. Adding a `key` on the list solves the issue

**Comment by Wei102193** [comment]
It is still the same in 1.4.0.

**Comment by ushyDev** [comment]
any updates?

**Comment by zyestin** [comment]
any updates?

**Comment by zyestin** [comment]
any updates?

**Comment by zyestin** [comment]
any updates?
