### ISSUE TITLE
Large frame drops when scrolling

### ISSUE THREAD

**Issue by sahil-ahuja-1** [Shopify/flash-list#636]
When I'm scrolling fast on my FlashList, large segments of the screen become black and have frame drops while the views are waiting to be recycled. Is there any way to avoid this? I wasn't seeing this behavior with flat list.

**Comment by YunsGeek** [comment]
same

**Comment by antilakash** [comment]
+1

**Comment by asamiz** [comment]
Same issue here

**Comment by wilhg** [comment]
Same here
