### ISSUE TITLE
Flash List did not update state

### ISSUE THREAD

**Issue by saqib00786** [Shopify/flash-list#641]
**Currently, I'm working on a project that is related to a commerce app and using context API so, when I update the state from context API flash list did not render the state that I mentioned in the context API but it's working perfect and producing correct result when I change flash list to flat list.**

`const { cartArray, setCartArray } = useGlobalContext();`

```
<View style={{ flex: 1, marginEnd: 4 }}>
                <TextInput
                  placeholder={'0'}
                  placeholderTextColor={"lightgray"}
                  mode="outlined"
                  outlineColor='lightgray'
                  keyboardType={'numeric'}
                  numberOfLines={1}
                  maxLength={4}
                  style={{ fontSize: 12, height: 35, lineHeight: 20 }}
                  value={cartArray[id]?.pack}
                  onChangeText={(val) => {
                    onInputChangeValue({ pack: val }, { ...item })
                  }
                  }
                />
              </View>
```

so when I called the onInputChangeValue method it did not update the cartArray and setCartArray

```
  const onInputChangeValue = (qty, product) => {
    let tempCart = {
      ...cartArray,
      [product.id]: { ...cartArray[product?.id], ...product, ...qty }
    }
    console.log("🚀 ~ file: PMI.js ~ line 20 ~ onInputChangeValue ~ tempCart", tempCart)
    setCartArray(tempCart);
  }
```

But if I change **Flash List** to **Flat List** It Work Well

**Comment by kaialsh705** [comment]
just pass extraData={this.state.extraData} in your FlashList

// and update this state when you need.
this.setState({
    extraData: !this.state.extraData
)}

**Comment by fortmarek** [comment]
`FlashList` rerenders only iff `data` or `extraData` changes. Any other change is ignored.

If you think this is a bug, you can create a new issue with proper reproduction steps that we can follow.
