### ISSUE TITLE
Swap elements

### ISSUE THREAD

**Issue by pranko17** [Shopify/flash-list#643]
I've noticed that sometimes when I swap elements, they don't swap, they just swap props between them. It seems to me that swapping them would be better, since a lot of logic is called inside the components based on changes in props. Or you can make this behavior optional.

**Comment by pranko17** [comment]
keyExtractor is valid.  I swap two elements and scroll without animation to the same element and see them update from the old element. And at console I see how changed props by item.

**Comment by fortmarek** [comment]
Can you provide reproduction steps here?
