### ISSUE TITLE
Color on <RefreshControl /> too light on flashlist

### ISSUE THREAD

**Issue by TowhidKashem** [Shopify/flash-list#645]
## Current behavior

The refresh contol's loader color is too light especially when used on a light background (barely visible):

<img width="414" alt="Screenshot 2022-10-23 at 11 58 09 PM" src="https://user-images.githubusercontent.com/1139927/197451986-f803eb93-65ba-4a85-b75d-385cae4fe88c.png">

Here's how it looks on a dark background (better):

<img width="414" alt="Screenshot 2022-10-23 at 11 59 39 PM" src="https://user-images.githubusercontent.com/1139927/197452006-e11df781-6695-4ee7-8a66-5904ce9d6261.png">

When I use a refresh control on a Flat list it looks normal (not this light).

Code:

```
<FlashList
  // etc...
  refreshControl={
    <RefreshControl
      tintColor="#000"
      refreshing={refreshing}
      onRefresh={onRefresh}
    />
  }
/>
```

## Expected behavior

The loader should be darker.

## Platform:

- [x ] iOS
- [ ] Android (not sure I only support IOS)

## Environment

1.1.0 (since it's compatible with expo SDK 46)
Expo managed workflow using custom dev client

**Comment by jvm-cognition** [comment]
@TowhidKashem  @fortmarek  has this issue been resolved? or could i potentially pick it up ?

**Comment by TowhidKashem** [comment]
@jvm-cognition hey the issue still exists as far as I can tell. Go for it if you want to take a shot at it! 🙏

**Comment by jvm-cognition** [comment]
@TowhidKashem would you mind assigning this to me? Thanks, will start soon.

**Comment by TowhidKashem** [comment]
> @TowhidKashem would you mind assigning this to me? Thanks, will start soon.

I'm not able to but perhaps @naqvitalha or @fortmarek can?
