### ISSUE TITLE
Cannot simultaneously scroll FlashLists

### ISSUE THREAD

**Issue by jonathancherry** [Shopify/flash-list#653]
If there are two FlashLists on the screen you cannot scroll them at the same time. Scrolling one blocks the scroll of another.

If you swap the components to FlatList they will both scroll fine simultaneously.

**Comment by UStojanovic1** [comment]
+1

**Comment by fortmarek** [comment]
Can you post a [Snack](https://snack.expo.dev/) sample? We otherwise can't fix the issue.

**Comment by naqvitalha** [comment]
Closing due to lack of sample.

**Comment by ChronoByteCosmonaut** [comment]
Same issue
