### ISSUE TITLE
Minimum deployment target ?

### ISSUE THREAD

**Issue by Developeranees** [Shopify/flash-list#678]
I'm trying to add [@shopify/flash-list](https://github.com/Shopify/flash-list) to my React Native app, and it gave me the following error:

Specs satisfying the `RNFlashList (from `../node_modules/@shopify/flash-list`)` dependency were found, but they required a higher minimum deployment target.

In my podfile I have platform :ios, '10.0'. Is there a way to find the minimum deployment target that this library requires? And is there ever a disadvantage to increasing the minimum deployment target?
<img width="880" alt="Screenshot 2022-11-18 at 3 02 22 PM" src="https://user-images.githubusercontent.com/43973272/202675516-a56eef80-82a4-4ba3-9266-f6fd7f7094c8.png">

**Comment by zhebil** [comment]
Same problem

**Comment by fortmarek** [comment]
> In my podfile I have platform :ios, '10.0'. Is there a way to find the minimum deployment target that this library requires? And is there ever a disadvantage to increasing the minimum deployment target?


Currently, React Native supports only iOS 12.4 higher. We technically support even [iOS 11 versions](https://github.com/Shopify/flash-list/blob/main/fixture/ios/Podfile#L4) but we have no plans to back-support also iOS 10.
