### ISSUE TITLE
Which value should I use when using margin to estimatedItemSize ?

### ISSUE THREAD

**Issue by shop-fluencer** [Shopify/flash-list#685]
Hello,

To improve Performance I have to set a value on estimatedItemSize.

Maybe I show 5 images. 100x100.

I set the value on estimatedItemSize 100. But when a image maybe has margin 12px. Should I write 112 to estimatedItemSize or should it stay 100 ?

**Comment by naqvitalha** [comment]
It should include everything. It's about about large a single list item is. In your case, it should be 112.
