### ISSUE TITLE
FlashList. columnWrapperStyle

### ISSUE THREAD

**Issue by Justin9606** [Shopify/flash-list#686]
Hi, I am using FlashList (vertical) base and i have set the number of columns 2 
and I need to add style like FlatList (columnWrapperStyle) for FlashList case but Seems it does not support

Is there any way to style the columnWrapper in FlashList?

**Comment by naqvitalha** [comment]
You can check out `overrideItemLayout` prop if you want to modify item span. You can provide a higher numColumn value and adjust spans.
There is no grouping in how FlashList does layout so there is no wrapper to style.

**Comment by fortmarek** [comment]
@BalogunofAfrica please create another issue or a GitHub discussion if you are still having issues with this.

**Comment by mrousavy** [comment]
Hey! Sorry for commenting on an old/closed issue, but I'm trying to figure out if it's supported to horizontally invert the order of items?

As in, I have a FlashList with `inverted={true}` and `numColumns={4}`.
Now the first item in the array is at the bottom left, when instead I want it to be on the bottom right (just like in iOS Photos).

In FlatList this can be solved by passing `transform: [{ scaleX: -1 }]` to `columnWrapperStyle`, then passing the same to each item. This is effectively doing the same thing as `inverted={true}`, but for the X axis.

Is that supported in FlashList?
