### ISSUE TITLE
MasonryFlashList onScroll callback doesn't change the value according to the component scope

### ISSUE THREAD

**Issue by gkartalis** [Shopify/flash-list#689]
## Current behavior

MasonryFlashList onScroll callback doesn't change the value according to the component scope, e.g. in the snack below we have a FlashList and a MasonryFlashList, you can see that even when we update the state the logs from the MasonryFlashList prints out the initial value while with the FlashList it prints the updated value.

https://snack.expo.dev/@gkartalis/humiliated-popcorn

## Expected behavior

MasonryFlashList and FlashList onScroll callback should behave the same way in both cases

## To Reproduce

snack with the issue repro
https://snack.expo.dev/@gkartalis/humiliated-popcorn

1. press any button to set the state
2. scroll the bottom list (flash list) and see the logs - log prints updated state value
3. scroll the top list (MasonryFlashList) and see the logs - log prints initial state value

## Platform:

- [x] iOS
- [x] Android

## Environment

1.4.0 in the snack
1.4.0 in react native 0.66.5 https://github.com/artsy/eigen/pull/7693

**Comment by gkartalis** [comment]
cc @pvinis

**Comment by ayoubechc** [comment]
@gkartalis you had find a solution ?
