### ISSUE TITLE
ScrollTo doesn't take paddingTop in account.

### ISSUE THREAD

**Issue by arjendevos** [Shopify/flash-list#702]
## Current behavior

```tsx
<FlashList
  contentContainerStyle={{ paddingBottom: insets.bottom, paddingTop: H_MAX_HEIGHT }}
  ref={ref}
  automaticallyAdjustContentInsets={true}
  keyboardDismissMode="on-drag"
  onScroll={onScroll}
  data={mappedProducts}
  estimatedItemSize={120}
  keyExtractor={(item) => {
    return `${item.id}`;
  }}
  renderItem={({ item }) => {
    return <ProductItem product={item} restaurant={restaurant} />;
  }}
/>
```

This is our flashlist. It contains a list of products. 

```tsx
onPress={(item) => {
  setSelectedCategory(item);
  ref.current?.scrollToItem({ item: item.name, animated: true });
}}
```
As you can see we have a paddingTop and paddingBottom. When we do not have those, the scrollTo works perfectly. But when we have padding, it completely forgets about those paddings and just ignores them while scrolling. So, when we scroll to an item, we end up with a different item.

```tsx
ref.current?.scrollToOffset({ offset: 10, animated: true });
```
^ScrollToOffset seems to acknowledge the padding.

```tsx
ref.current?.scrollToIndex({ index: 0, animated: true });
```
^ScrollToIndex & scrollToItem does not acknowledge the padding. 

## Expected behavior

ScrollTo should take in account for the padding.

## Platform:

- [x] iOS
- [x] Android

## Environment

`"@shopify/flash-list": "1.1.0",`

**Comment by naqvitalha** [comment]
Can you provide a repro on expo snack? I'll be able to quickly take a look. This was verified to work in our testing.

**Comment by arjendevos** [comment]
@naqvitalha https://snack.expo.dev/@degroteverleiding/nervous-macaroni-and-cheese

**Comment by naqvitalha** [comment]
In your sample, the list is starting from the top of the screen. And padding is being considered during the scroll. I've moved the overlay to the bottom to make you realize what's going on. Item no. 6 is going to the top as expected: https://snack.expo.dev/@naqvitalha/nervous-macaroni-and-cheese---fixed
Close the issue if this helps!

**Comment by arjendevos** [comment]
Yeah but we actually don't want it to go to the top. We want the item to go to the top - padding top

**Comment by naqvitalha** [comment]
You can pass your paddingTop value as viewOffset when you call scrollToIndex.
The current API behavior is what we expect.

**Comment by arjendevos** [comment]
Ah oke! Thank you very much!
