### ISSUE TITLE
scrollTo doesn't work with a custom scroll component

### ISSUE THREAD

**Issue by arjendevos** [Shopify/flash-list#713]
## Current behavior
`ref.current.scrollToItem` (or `scrollToIndex`) does not work when we pass a custom scroll component in the `renderScrollComponent` prop.

https://snack.expo.dev/@degroteverleiding/nervous-macaroni-and-cheese---fixed

That we still can scroll to the item or index.

## Platform:

- [x] iOS
- [x] Android

## Environment

`1.4.0`

**Comment by arjendevos** [comment]
Solution: 
```tsx
const CustomScroller = React.forwardRef((props, ref) => {  
    return <ScrollView ref={ref} {...props}/>;
})
```

**Comment by arjendevos** [comment]
With typescript it gives a lot of errors and it still doesn't work. Weird that it works in the expo snack but not in my app.

**Comment by arjendevos** [comment]
```tsx
  const renderScrollComponent = React.forwardRef((props, ref) => (
    <Animated.ScrollView {...props} onScroll={scrollHandler} ref={ref} />
  ));
```

This is what i do in my app

**Comment by arjendevos** [comment]
SOLUTION: THIS SHOULD BE OUTSIDE COMPONENT

**Comment by RRaideRR** [comment]
Just had the same problem. For me it was even simpler because I needed the ScrollView from react-native-gesture-handler. The following code gives no TS errors

```
import {
  ScrollView,
} from 'react-native-gesture-handler';

... 

<FlashList 
   ...
   renderScrollComponent={ScrollView}
```
