### ISSUE TITLE
Can only see last HALF item when keyboard is open

### ISSUE THREAD

**Issue by shop-fluencer** [Shopify/flash-list#717]
## Current behavior

If my Keyboard is active and I scroll to the last item I can not see the full item only the half.

## Expected behavior

...

## To Reproduce

```
    <View style={s.container}>
      <SearchInput 
        value={search}
        onChangeText={handleChangeSearchText}
        onPressSearched={() => {}}
        onPressClearTextField={handleClearTextField}
        style={s.inputSearch}
       />
       <FlashList 
         data={data}
         keyExtractor={(item, i) => item.id.toString()}
         renderItem={renderItem}
         keyboardShouldPersistTaps='handled'
         estimatedItemSize={290.7}
        />
   </View>
```

## Platform:

- [x ] iOS
- [x ] Android

## Environment

Shopify V. 1.3.1

![WhatsApp Image 2022-12-21 at 02 45 53](https://user-images.githubusercontent.com/101994056/208801501-28a89e2d-b6b4-4f65-a124-f13169ba2c46.jpeg)

**Comment by fortmarek** [comment]
Hey, can you provide full reproduction steps? It would help us debug this issue 🙏

**Comment by jayant-lumino** [comment]
Getting the same issue, Any workaround?

[

https://github.com/Shopify/flash-list/assets/74182056/35bc87a5-11f3-477c-a548-daca17b44140

](url)

**Comment by longhaha1998** [comment]
It has been closed this as completed,how to solve it?

**Comment by longhaha1998** [comment]
> Hey, can you provide full reproduction steps? It would help us debug this issue 🙏


It has been closed this as completed,how to solve it?
