### ISSUE TITLE
Sticky List Header Not Working With React Navigation Header

### ISSUE THREAD

**Issue by branaust** [Shopify/flash-list#726]
## Current behavior

I'm rendering a FlashList with `stickyHeaderIndices` enabled. I've just copy and pasted from the documentation and am unable to get headers to stick below the header. 

https://user-images.githubusercontent.com/61210295/210037970-620c89d1-5942-40f5-a0e3-17b1d0cfb094.MP4

FlashList Component: 

```
import { FlashList } from '@shopify/flash-list';
import React from 'react';
import { Dimensions, StyleSheet, View } from 'react-native';

interface Contact {
  firstName: string;
  lastName: string;
}

const contacts: (string | Contact)[] = [
  'A',
  { firstName: 'John', lastName: 'Aaron' },
  'D',
  { firstName: 'John', lastName: 'Doe' },
  { firstName: 'Mary', lastName: 'Dianne' },
];

const stickyHeaderIndices = contacts
  .map((item, index) => {
    if (typeof item === 'string') {
      return index;
    } else {
      return null;
    }
  })
  .filter((item) => item !== null) as number[];

const ExerciseFlashList = () => {
  return (
    <FlashList
      data={contacts}
      renderItem={({ item }) => {
        if (typeof item === 'string') {
          // Rendering header
          return (
            <Typography textStyle={styles.header} variant="helper">
              {item}
            </Typography>
          );
        } else {
          // Render item
          return <Typography variant="body">{item.lastName}</Typography>;
        }
      }}
      getItemType={(item) => {
        // To achieve better performance, specify the type based on the item
        return typeof item === 'string' ? 'sectionHeader' : 'row';
      }}
      estimatedItemSize={100}
      stickyHeaderIndices={stickyHeaderIndices}
      contentInsetAdjustmentBehavior="always"
    />
  );
};

const styles = StyleSheet.create({
  header: {
    fontSize: 32,
    backgroundColor: '#fff',
  },
});

export default ExerciseFlashList;
```

And this is where I'm rendering the FlashList:
```
<View
      style={{ height: '100%', width: Dimensions.get('screen').width }}>
      <ExerciseFlashList />
    </View>
```

## Expected behavior

I expect the sticky list headers to stick to the bottom of the navigation header

## Platform:

- [x] iOS
- [ ] Android

## Environment

    "@shopify/flash-list": "1.3.1"

**Comment by atultiwaree** [comment]
+1

**Comment by alizahid** [comment]
Looked into this a bit more. Doesn't seem like a react-navigation issue.

Take a look at this video.

https://github.com/user-attachments/assets/1962ced3-9b21-4449-9c27-7de491bf9bc5

The sticky header does indeed work. You just can't see it before it's hidden behind the header.

I'm using a transparent header, so I can see the sticky working.

In the second part of the video (after the refreshing toast), I add some styling based on `target === 'StickyHeader'` and it gives me what I need but that doesn't kick in soon enough.

With my screen setup, I have to add `progressViewOffset` and custom values for `scrollIndicatorInsets` so the FlashList works with my absolutely positioned header and tab bar. But there's no option to add an offset for the sticky header.

@fortmarek Any help?

**Comment by akamfoad** [comment]
@fortmarek as @alizahid demonstrated this is not an issue with React Navigation, I think its probably related to window correction logic in FlashList.

The issue here is that there is no way (at least not documented way) to provide a transformation value to what the sticky header anchors to, for example, react navigation provides [`useHeaderHight`](https://reactnavigation.org/docs/elements/#useheaderheight) which gives you the current height of the header and changes based on the size as you scroll or else.

If FlashList could accept such value as a prop and apply it before laying out the sticky items, it'd easily solve this issue imo.

**Comment by hugoecken** [comment]
Any update on this ?

**Comment by branaust** [comment]
use legend listEm 29 de set. de 2025, à(s) 13:27, Hugo Eckenschwiller ***@***.***> escreveu:﻿hugoecken left a comment (Shopify/flash-list#726)
Any update on this ?
