### ISSUE TITLE
Data inside renderItem is shared with other items

### ISSUE THREAD

**Issue by adscud** [Shopify/flash-list#728]
## Current behavior

Hello, I have faced a strange bug. 
Data inside the `renderItem` function is shared between each others.
For example, I have a state `showSquare` which is only `true` when `index === 0`. You will see inside the video, the square will be present on the indexes `0, 3, 6` and it can continue like that if I add data.
It happens every `3 items`.

https://user-images.githubusercontent.com/34245352/210756986-3d4649c9-54a3-49e5-9e4a-4281eba18270.mp4

## Expected behavior

The square should be present only on the first index.

## To Reproduce

You can use this repository to reproduce the bug, I use it to record the bug.
https://github.com/adscud/flash-list-bug

## Platform:

- [X] iOS
- [X] Android

## Environment

```
    "@shopify/flash-list": "1.3.1", // ⚠️ IT ALSO HAPPENS WITH THE `1.4.0`
    "expo": "~47.0.9",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-web": "~0.18.9"
```

⚠️ IT ALSO HAPPENS WITH THE `1.4.0`

**Comment by vikingprank** [comment]
I have the same problem, what was the fix? Cheers
