### ISSUE TITLE
MasonryFlashList doesn't work

### ISSUE THREAD

**Issue by Bayramito** [Shopify/flash-list#744]
Simply MasonryFlashList doesn't work at all with 1.4.0

**Comment by fadymach** [comment]
![image](https://user-images.githubusercontent.com/15573103/214400001-97238b5e-ea89-4e41-aa29-6540f947ccb3.png)

**Comment by Slapbox** [comment]
@Bayramito you should include details about the error it's showing, or if there's no error at least explain in what way it fails.

**Comment by fortmarek** [comment]
Closing, we need a reproduction in Snack to debug.
