### ISSUE TITLE
Wrong images loaded when scrolling (need to wait a little for the correct images to load)

### ISSUE THREAD

**Issue by akoQassym** [Shopify/flash-list#749]
## Current behavior

I have a flashlist of View elements, which display information about the products (cover photo, name, price). Whilst scrolling the wrong images of the items are shown. Only after waiting a little bit, the correct images replace the wrong ones, and everything looks as it's supposed to look.

I assume this happens because of the Recycling, since FlashList does not destroy the item when an item gets out of the viewport, but re-renders the component with a different item prop. Thus, while scrolling, the previous version of the image shown while the new one is being loaded.

## Expected behavior

Scrolling should not affect how images are displayed: each corresponding image should be displayed correctly.

## Platform:

Both iOS and Android

## Environment

1.3.1

**Comment by fortmarek** [comment]
Hey!

As you mention, this is due to recycling. You will need to reset the currently loaded image to show a placeholder until the image loads when an item is recycled. You can follow the instructions [here](https://shopify.github.io/flash-list/docs/recycling).

**Comment by Brma1048** [comment]
@fortmarek I have the same issue but i do not understand how i can reset my currently loaded image. I can add a key prop to my image and set it like this: 
`if (item.id !== lastItemId.current) {
      lastItemId.current = item.id;
      setImageKey(prev => prev + 1);
   }`
   
   But [here](https://shopify.github.io/flash-list/docs/fundamentals/performant-components) they say : **"Using key prop inside your item and item's nested components will highly degrade performance."**

**Comment by BenQoder** [comment]
FlashList, Recycles or Reuses Render Items, the reason you are not getting the correct images is because you are setting the image in state within the render item, FlashList advises against it but if you must, you need to update the state again when item is reused.

My explanation may not be clear but I'll reference the doc

**Comment by AndreiTimofte96** [comment]
did you guys found any solution @badalsaibo @codegabk @BenQoder ... I m not using state and still the expo image loads after a couple of milliseconds.... already used `recyclingKey={id}`.

**Comment by AndreiTimofte96** [comment]
noticed it's only happening when passing a placeholder. seems like it's only recycling the source and not the placeholder


  <Image
        style={styles.image}
        source={preloadImage ? imageSource : imageThumb}
        // {...(preloadImage ? { placeholder: imageThumb } : {})}
        recyclingKey={id}
      />

**Comment by IgorBialek** [comment]
@badalsaibo Cloud you please share your solution ?

**Comment by paragbarsar99** [comment]
> @AndreiTimofte96 I conditionally added a key prop on the Image tag only for iOS for now.
> 
> I use a custom image component which is just a wrapper to the image for my specific needs.
> 
> I also can't use the `recyclingKey` prop since I'm in a RN CLI project.

can you please share your custom image component code or anything related to this ?

**Comment by naqvitalha** [comment]
I'd recommend using expo-image or FastImage (there's a fork that's well maintained). You can also do something like the following:

```
import React, { useMemo, useRef } from "react";
import { Animated, Image, ImageProps, Platform } from "react-native";

interface RecyclingImageProps extends Omit<ImageProps, "source"> {
  source: { uri?: string };
}
const isIOS = Platform.OS === "ios";

const RecyclingImageIOS = (props: RecyclingImageProps) => {
  const animatedOpacity = useRef(new Animated.Value(0)).current;

  useMemo(() => {
    animatedOpacity.setValue(0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [props.source.uri]);

  return (
    <Animated.Image
      {...props}
      style={[props.style, { opacity: animatedOpacity }]}
      onLoad={() => {
        animatedOpacity.setValue(1);
      }}
    />
  );
};

const RecyclingImageAndroid = (props: RecyclingImageProps) => {
  return <Image {...props} />;
};

export const RecyclingImage = isIOS ? RecyclingImageIOS : RecyclingImageAndroid;
```
