### ISSUE TITLE
Inverted scroll super laggy on Android

### ISSUE THREAD

**Issue by devoren** [Shopify/flash-list#751]
I want to use a  flashlist to show a inverted list. But if I use inverted prop on android it works very slow.
Default Flashlist: drops 5-10 FPS in dev mode (UI 60FPS)
Inverted Flashlist: drops 30-40 FPS in dev mode (UI also 20-40FPS)

```
const renderItem: ListRenderItem<IMessage> = ({ item, index }) => {
	return (
		<MessageItem id={item.id} message={item.message} date={item.date} />
	)};

 const keyExtractor = ({ id, date }: IMessage) => `${id}_${date}`;

 return (
	<SafeAreaView style={styles.container}>
		<FlashList
			ref={list}
			data={messages}
			keyExtractor={keyExtractor}
			renderItem={renderItem}
			contentContainerStyle={{
				paddingVertical: SCALE.XS,
			}}
			showsVerticalScrollIndicator={false}
                        estimatedItemSize={100}
		/>
	</SafeAreaView>
  );
```

## Current behavior

[inverted.webm](https://user-images.githubusercontent.com/99968085/216315189-47eef7bc-5d3b-4390-a06c-54ce1ad48b5a.webm)

## Expected behavior
UI 60 FPS

## To Reproduce

The flatlist also has the same behavior but after using [this](https://github.com/facebook/react-native/issues/30034#issuecomment-1411922104) patch UI stable 60fps but not working with FlashList
## Platform:

- [ ] iOS
- [+] Android

## Environment

1.4.1

**Comment by CaptainJeff** [comment]
Same issue

**Comment by naqvitalha** [comment]
I'm looking into this.

**Comment by devoren** [comment]
@CaptainJeff What if we change this  code 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/99968085/216997028-529714e1-3743-486f-bd1b-0a1eca36add4.png">
 
 to this code ( flatlist solution ):
 Platform.OS === 'android' ? { scaleY: -1 } : { transform: [{scaleY: -1}] }

**Comment by CaptainJeff** [comment]
Yeah @devoren that's pretty much my current temporary solution. I was doing a patch-package on the react-native library for `transformStyle` but just switched it to patch just this dependency. It does seem to work.

@naqvitalha maybe it makes sense to update this in the project? I just opened a PR https://github.com/Shopify/flash-list/pull/755

**Comment by CaptainJeff** [comment]
@devoren Just to clarify. Are you setting that in the index.js of the root of your app? Not in this dependency, right?

**Comment by devoren** [comment]
@CaptainJeff Flashlist lags again, but flat list works correctly

**Comment by devoren** [comment]
@naqvitalha It didn't help in my case, but if I use a flat list and add ViewReactNativeStyleAttributes in index.js it works correctly (without attribute inverted prop not working)

**Comment by fukemy** [comment]
Hi can someone tell me which better between`{ scaleY: -1}` and `{ transform: [{ rotate: "180deg" }] }`

**Comment by fukemy** [comment]
@devoren thanks you, I am using `{ scaleY: -1}`, it's work fine too. I dont know how to compare the performance between them to choose the best solution

**Comment by irisjae** [comment]
With the current inverted list transforms, on Android, the scrollbar is inverted (on the left side, when it should be on the right). The upstream react-native patch (https://github.com/facebook/react-native/commit/3dd816c6b7bcd9cc4c21199f0b645755fb97f50f) suggests that we should pass `isInvertedVirtualizedList` to the inner ScrollView when using inverted lists on Android.

Perhaps we should add that to the inner ScrollView on `inverted={true}`? For the meantime, the user can workaround this by adding `overrideProps={{ isInvertedVirtualizedList: true }}` to the FlashList.
