### ISSUE TITLE
Not rendering items when horizontal

### ISSUE THREAD

**Issue by gabrielbarbosanascimento** [Shopify/flash-list#757]
## Current behavior
I'm implementing a horizontal ruler, so the user can set they height. But the initial render is empty (of the ruler steps). If I scroll slow, it stills, but when I scroll fast, they finally appear

```javascript
<FlashList
          ref={ref}
          horizontal
          estimatedItemSize={STEP_SIZE}
          estimatedListSize={{ height: STEP_SIZE * 2, width: WIDTH }}
          bounces={false}
          keyExtractor={(item) => `${item}`}
          removeClippedSubviews={true}
          contentContainerStyle={{
            paddingLeft: WIDTH / 2 - 10,
            paddingRight: WIDTH / 2
          }}
          showsHorizontalScrollIndicator={false}
          data={values}
          onScroll={(e) => {
            onScroll(e.nativeEvent.contentOffset.x);
          }}
          onMomentumScrollEnd={(e) =>
            scrollToNearbyPosition(e.nativeEvent.contentOffset.x)
          }
          renderItem={({ index }) => (
            <View style={styles.step_container}>
              <View style={index % 5 === 0 ? styles.step : styles.step_small} />
            </View>
          )}
        />
```

## Expected behavior
This doesn't happen when its vertically. I double checked the sizes (they are all fixed values)

## To Reproduce

I recorded a video of this behavior

https://user-images.githubusercontent.com/3287403/217355405-78465767-c201-42b4-96ed-6d0e41600105.mp4

## Environment

"@shopify/flash-list": "1.3.1"
"expo": "~47.0.7",

**Comment by frankbaele** [comment]
I had a similar issue with the horizontal mode of the flashlist. Figured out that the initial length of my array was 0. This was my quick fix-> only render the flashlist if there are items.
```
  if (values.length == 0) {
    return (
      <View>
        <Text>{'test'}</Text>
      </View>
    );
  }
  return <FlashList data={values} horizontal={true} />;

**Comment by gabrielbarbosanascimento** [comment]
@frankbaele I just tested it, your workaround is working like a charm. Thank you!

**Comment by ducnguyen4301** [comment]
> I had a similar issue with the horizontal mode of flashlist. Figured out that the initial length of my array was 0. This was my quick fix-> only render the flashlist if there are items. Hope this helps you out.
> 
> ```
>   if (values.length == 0) {
>     return (
>       <View>
>         <Text>{'test'}</Text>
>       </View>
>     );
>   }
>   return <FlashList data={values} horizontal={true} />;
> ```
i have same issue here and i try it, but don't work for me

**Comment by fortmarek** [comment]
Hey,

This is a specific variant of [this](https://github.com/Shopify/flash-list/issues/581) issue where the initial height is 0 and then non-zero. I will close this a duplicate, for now, we recommend using the suggested workaround.
