### ISSUE TITLE
Whole list rerenders when new data is inserted at the start

### ISSUE THREAD

**Issue by SamuelScheit** [Shopify/flash-list#768]
## Current behavior

All items of the FlashList will get rendered if new data is inserted at the start,
but if new data is inserted at the end of the array only the new item will get rerendered.

https://user-images.githubusercontent.com/34555296/219814435-f4430304-69f4-41bd-9456-868d04b16b25.mov

## Expected behavior

It should only rerender the newly added item regardless of insert position.

## To Reproduce

```js
import React from "react";
import { View, Text, Button, SafeAreaView } from "react-native";
import { FlashList } from "@shopify/flash-list";

export default function Test(props: any) {
	const [data, setData] = React.useState([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);

	return (
		<SafeAreaView style={{ flex: 1 }}>
			<FlashList data={data} renderItem={renderItem} />

			<Button title="Add start" onPress={() => setData([data.length, ...data])} />
			<Button title="Add end" onPress={() => setData([...data, data.length])} />
		</SafeAreaView>
	);
}

const renderItem = (props: any) => {
	console.log("render", props.index);

	return <Text>{props.item}</Text>;
};
```

## Platform:

- [x] iOS
- [ ] Android (did not test)

## Environment

- @shopify/flash-list version 1.4.1
- react-native 0.71.0
- iOS 16.3.1

**Comment by SamuelScheit** [comment]
It seems like this might be caused by the underlying `recyclerlistview` package which rerenders all items in the list, because the data of the recycler list item changes:
e.g. list state at the start:
```
index 0 -> 0
index 1 -> 1
index 2 -> 2
```

list state after insertion:
```
index 0 -> 3
index 1 -> 0
index 2 -> 1
index 3 -> 2
```

The recycler list view package has some props, which could be used to detect this kind of state change and prevent the list from rerendering all items:
- dataHasChanged
- syncAndGetKey

Alternatives I've tried was to assign the new element a negative index (-1, -2, ...), but they don't render at all.

**Comment by SamuelScheit** [comment]
Ok it seems like using `react.memo` solves this issue.
Sadly the renderItem function can't be wrapped directly and a helper render function needs to be created.

Updated code:
```js
import React from 'react';
import { View, Text, Button, SafeAreaView } from 'react-native';
import { FlashList } from '@shopify/flash-list';

export default function Test(props: any) {
  const [data, setData] = React.useState([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);

  return (
    <SafeAreaView style={{ flex: 1 }}>
      <FlashList
        keyExtractor={(x) => x.toString()}
        data={data}
        renderItem={renderItem}
      />
      <Button
        title="Add start"
        onPress={() => setData([data.length, ...data])}
      />
      <Button title="Add end" onPress={() => setData([...data, data.length])} />
    </SafeAreaView>
  );
}

const TestItem = React.memo(function TestItem(props) {
  console.log('render', props.index);
  return <Text>{props.item}</Text>
}, (p, n) => p.item === n.item)

const renderItem = (props: any) => {
  return <TestItem {...props} />;
};
```

**Comment by ramssutharr** [comment]
I'm having the same issue. @SamuelScheit your solution didn’t work for me . did you find any other solution ?

**Comment by SamuelScheit** [comment]
@ramssutharr it only partially rerenders, flash-list actually calls the renderItem function, but because the component is wrapped in React.memo it skips it, because the props didn't change.
you can pass a function to [React.memo](https://react.dev/reference/react/memo) that compares the old and new props and returns a boolean to indicate whether or not they changed.
example taken from the react docs:
```js
const Chart = memo(function Chart({ dataPoints }) {
  // only rerenders, when props changed
}, arePropsEqual);

function arePropsEqual(oldProps, newProps) {
  return (
    oldProps.dataPoints.length === newProps.dataPoints.length
  );
}
```
