### ISSUE TITLE
Android build fails with react native 0.71 - please update kotlin version

### ISSUE THREAD

**Issue by youssdevx** [Shopify/flash-list#777]
## Current behavior

Build fails on Android

<img width="845" alt="image" src="https://user-images.githubusercontent.com/21293851/222473513-a243c6c0-6027-463b-8a35-5a2ab523e0df.png">

## Expected behavior

Build should succeed

## To Reproduce

Upgrade to React native 0.71 and build on Android

## Platform:

- [ ] iOS
- [X] Android

## Environment

- "@shopify/flash-list": "1.4.1"
- React Native version: **0.71.3**
- Expo SDK 48

## How to fix

In `android/build.gradle` modify:
`ext._kotlinVersion = rootProject.ext.has("kotlinVersion") ?  rootProject.ext.get('kotlinVersion') : '1.6.20'`

**Comment by brunosp-49** [comment]
Hi men, I'm getting the same error, I tried to copy your solution but it's still not working, have you changed something else?

**Comment by Maria4lexzy** [comment]
Worked for me as well, I changed it from kotlin_version to kotlinVersion and it works

my `android/build.gradle`
`  ext {
        ...
        kotlinVersion = '1.7.10'
        }
 dependencies {
    ...
    classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion')
  }`

**Comment by kursatalgul** [comment]
> Worked for me as well, I changed it from kotlin_version to kotlinVersion and it works
> 
> my `android/build.gradle` ` ext { ... kotlinVersion = '1.7.10' }` `dependencies { ... classpath('org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion') }`


Is it expo ? because There is no android folder in Expo

**Comment by techvfxking** [comment]
It happened with me also using react native cli
