### ISSUE TITLE
Masonry List Buggy When Filtering

### ISSUE THREAD

**Issue by enchorb** [Shopify/flash-list#778]
## Current behavior

When having the FlashList MasonryList data source hooked up to a search/filter bar, on searches sometimes items wont render, bottom of cards will be cut-off, etc. 

## Expected behavior

Using the FlatList from React Native this does not happen

## Platform:

- [x] iOS
- [ ] Android

## Environment

1.4.1

**Comment by fortmarek** [comment]
Please, provide a reproducible sample.

**Comment by naqvitalha** [comment]
Closing due to lack of sample.

**Comment by EuSet** [comment]
@naqvitalha hi, there is an expo snack and a video in a [new ticket ](https://github.com/Shopify/flash-list/issues/1255#issue-2383677404)
