### ISSUE TITLE
Maybe estimatedItemSize should be renamed to estimatedItemHeight

### ISSUE THREAD

**Issue by aureosouza** [Shopify/flash-list#780]
With current naming developers may think that this is the estimated input array lenght

**Comment by mobinni** [comment]
I thought exactly that 😅

**Comment by b0iq** [comment]
Using size instead of height to use the same prop for horizontal layout.

**Comment by bryanltobing** [comment]
that is why my onEndReached always gets triggered. I really thought it was for the size of the data

**Comment by fortmarek** [comment]
The documentation should make this clear. We don't plan to rename this prop now.
