### ISSUE TITLE
Blank cells when views look alike

### ISSUE THREAD

**Issue by cozmoc** [Shopify/flash-list#783]
## Current behavior

2 similar looking cells/views in the list will cause one of them to be shown as blank if not in the same scrolling area.

## Expected behavior

all views should be visible regardless of the way they look, or props passed to them.

## To Reproduce

1. create a flashlist with 50 items, each one has it's index rendered (from 1-50)
2. adjust one of the views rendered to show exact number to another one from the list 

for example: 
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ................... , 42, 9, 43, 44, 45, 46, 47, 48, 49, 50
                                                                                          ^
3. observe the second view (9) will be hidden and shown as a blank

screenshot - (first comment with `5` is shown while the other is blank)

![Simulator Screen Shot - iPhone 14 - 2023-03-08 at 15 09 35](https://user-images.githubusercontent.com/13244434/223750783-17351c07-959c-4cbd-92d6-43025c8d1f72.png)

## Platform:

- [x] iOS
- [ ] Android

## Environment

1.4.0

**Comment by Jlexyc** [comment]
I had this problem in a long paginated list. The reason of it was a collision of the same keys. We had a problem on BE side when it for some reason were returning the same models within 2 different pages.
So pay attention on your keys and keyExtractor.

**Comment by cozmoc** [comment]
> I had this problem in a long paginated list. The reason of it was a collision of the same keys. We had a problem on BE side when it for some reason were returning the same models within 2 different pages. So pay attention on your keys and keyExtractor.

Thanks for the solution! changing to `key={id}` instead of `key={index}` fixed the issue for me.
