### ISSUE TITLE
onEndReached gets called on empty data

### ISSUE THREAD

**Issue by bryanltobing** [Shopify/flash-list#790]
## Current behavior

FlashList by Shopify `onEndReached` gets called when data is still empty whereas FlatList by react native isn't

![image](https://user-images.githubusercontent.com/46083126/226100371-ffa1a7e3-6148-4d5e-8fa8-c646ee3a0d0f.png)

## Expected behavior

onEndReached in FlashList should not be called when data is empty or when we are still waiting for the data resolved from api, also since  default `FlatList` by react native doesn't do that 

## To Reproduce

Here is the snack: https://snack.expo.dev/@bryanltobing/d9b5dd

comment and uncomment `FlashListTest` and `FlatListTest`. you will notice that the alert that is called is the alert in onEndReached by FlashList

## Platform:

- [x] iOS
- [x] Android

## Environment

1.3.1
1.4.1

**Comment by fortmarek** [comment]
`onEndReached` should technically be called when data is empty. Changing this could be a bigger regression and it's not worth now to align with `FlatList`. You should be able to cater for this in your code quite easily by checking whether the data is empty or not.
