### ISSUE TITLE
The height of items are not equal when numColumns > 1

### ISSUE THREAD

**Issue by pnthach95** [Shopify/flash-list#797]
## Current behavior

I have a list with `numColumns={2}`. Item has `flex: 1` to make it show full width and height. But the height is not equal if number of lines of text of items are different in a row. See `One Special Day Fumi` at middle of screenshot.

![image](https://user-images.githubusercontent.com/31266357/226794375-7eb8c8a9-f74a-42b9-b5af-6070ce40a140.png)

## Expected behavior

Items in a row should have same height, like in `FlatList`

![image](https://user-images.githubusercontent.com/31266357/226794361-d2cbe1dc-7632-47bb-a68a-df5982bd7459.png)

## To Reproduce

https://snack.expo.dev/@pnthach95/flashlist

## Platform:

- [x] iOS
- [x] Android

## Environment

1.4.2

**Comment by Darren120** [comment]
updates?

**Comment by martijnmichel** [comment]
+1 same issue

**Comment by truongtv22** [comment]
same issue :(

**Comment by shawhu** [comment]
even with the same height, flashlist doesn't support numColumns>1, I've tested. when numColumns>1, the stickyhead will cover the first row, I mean on top of it.


    renderItem={({ item }) => {
          if (item.id === "0") {
            // Sticky Head
            return (
              <View style={{ backgroundColor: "red", width: screenWidth, height: 100 }}></View>
            } else {
            //Normal grid
            return (
              <View style={{ backgroundColor: "green", width: screenWidth, height: 150, margin: 5 }}></View>
           );
          }
        }}




![Image](https://github.com/user-attachments/assets/40fbf477-b9e4-4cb8-8ebc-c69469c06a05)

**Comment by Veeksi** [comment]
> even with the same height, flashlist doesn't support numColumns>1, I've tested. when numColumns>1, the stickyhead will cover the first row, I mean on top of it. and if numColumns=1, then, everything is fine. So...don't tell me this is by design. It's clearly a bug. Or maybe just say it on the doc, that flashlist doesn't fully support numColumns>1 situations...
> 
> ```
> renderItem={({ item }) => {
>       if (item.id === "0") {
>         // Sticky Head
>         return (
>           <View style={{ backgroundColor: "red", width: screenWidth, height: 100 }}></View>
>         } else {
>         //Normal grid
>         return (
>           <View style={{ backgroundColor: "green", width: screenWidth, height: 150, margin: 5 }}></View>
>        );
>       }
>     }}
> ```
> 
> ![Image](https://github.com/user-attachments/assets/40fbf477-b9e4-4cb8-8ebc-c69469c06a05)

Having this same issue when displaying 3 images in a same row. A bit weird that issue like still exists
