### ISSUE TITLE
Task :shopify_flash-list:testDebugUnitTest FAILED

### ISSUE THREAD

**Issue by abdullahIsa** [Shopify/flash-list#799]
Hello i updated flashList to the latest version and getting this when i do ./gradlew build, how to fix?

## Current behavior

![image](https://user-images.githubusercontent.com/49385380/227474317-a05b2cb4-ed49-4301-83af-cc1e062459e9.png)

## Expected behavior

To build correctly without errors.

## To Reproduce

Install "@shopify/flash-list": "^1.4.2" with "react-native": "0.70.6"

## Platform:

- [ ] iOS
- [ yes] Android

## Environment

"@shopify/flash-list": "^1.4.2"
"react-native": "0.70.6"

**Comment by andrespch** [comment]
Hey @abdullahIsa, can you please provide an example project that demonstrates this issue?  we would then try to look into this soon.

**Comment by abdullahIsa** [comment]
> Hey @abdullahIsa, can you please provide an example project that demonstrates this issue? we would then try to look into this soon.

Hello, i downgraded back to "@shopify/flash-list": "^1.4.1" since not getting the error so not sure what cause it in the latest version.

**Comment by shensven** [comment]
same one, see more detail here https://github.com/Shopify/flash-list/issues/756#issuecomment-1501180182
