### ISSUE TITLE
Flash-List not working properly after upgrading React Native to version 0.71.6 (Possible stableId collision)

### ISSUE THREAD

**Issue by ivan-zeller** [Shopify/flash-list#812]
**Description:**
Previously, our app was using flash-list (v. 1.4.2) as a replacement for SectionList from React Native (v. 0.71.5, old architecture) and it was working well. However, after upgrading to React Native version 0.71.6, we have noticed that our list that uses flash-list is broken. The layout is incorrect and some items are not shown. Additionally, we have observed a warning message after mounting and scrolling, which reads "Possible stableId collision".

**Steps to Reproduce:**
1. Upgrade React Native version to 0.71.6
2. Use flash-list in the app as a replacement for SectionList
3. Observe the list and scroll through it

**Expected Result:**
The list should display all items properly without any layout issues or warnings.

**Actual Result:**
The list is broken and some items are not displayed properly. A warning message appears after mounting and scrolling, indicating a possible stableId collision.

**Versions:**
- React Native: 0.71.6
- Flash-List: 1.4.2

**Additional Information:**
We have not encountered this issue with previous versions of React Native and flash-list. We suspect that the issue may be related to changes in the architecture of React Native version 0.71.6.
![Simulator Screen Shot - iPhone 14 Pro - 2023-04-12 at 18 45 28](https://user-images.githubusercontent.com/113613406/231721079-209f3b8a-7227-411c-ba8d-b706bd1fdf76.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-04-12 at 19 48 39](https://user-images.githubusercontent.com/113613406/231721086-632ae471-67d7-4e57-94c1-6c493742a5ea.png)

**Comment by ivan-zeller** [comment]
@filippobarcellos I haven't fix it yet

**Comment by ivan-zeller** [comment]
@filippobarcellos Just change the version to 1.4.1 and it works well

**Comment by ivan-zeller** [comment]
@naqvitalha Yes, thanks you. The problem was duplicate ids

**Comment by damieng57** [comment]
I solved this issue with .slice(0) for data:
ex: `<FlashList
        ref={flatListRef}
        estimatedItemSize={80}
        keyExtractor={_getKey}
        renderItem={_renderItem}
        data={resultSet.slice(0)}
        ...
      />`

The key extractor was correctly defined.

**Comment by chr4ss12** [comment]
had same issue, no actual collisions between duplicate IDs and key extractors make sense,

fixed it doing deep copy over my results when adding new item to the list: 

```
_.cloneDeep(results)
```
