### ISSUE TITLE
FlashList scrolling works intermittently

### ISSUE THREAD

**Issue by KolissnikBogdan** [Shopify/flash-list#813]
## Current behavior

Hello everybody! When I scroll the list without taking my finger off the screen, scrolling works fine. After I stop scrolling, the scroll works only after performing a certain number of gestures (although this is not entirely true). I have not yet tested this functionality on ios, but for now I can definitely assure that this problem is reproduced on Android 12 and 13. This problem is reproduced both in the release build and in debug mode.

## Expected behavior

The scroll should work validly.

## To Reproduce

When creating my "ContactsFlashList" component, I used your project - https://github.com/Shopify/flash-list/blob/main/fixture/src/contacts/Contacts.tsx as an example. I did not make any additional changes to the components. The data is generated according to the provided documentation - https://shopify.github.io/flash-list/docs/guides/section-list.

## Platform:

- [ ] iOS
- [x] Android

## Environment

Versions:

- React Native: 0.71.4
- Flash-List: 1.4.2
- Android 12-13

ContactsFlashList.tsx
```
import React from 'react';
import {FlashList} from '@shopify/flash-list';

import ContactSectionHeader from './ContactSectionHeader';
import ContactCell from './NewListItem';
import ContactDivider from './ContactDivider';
import ContactHeader from './ContactHeader';

const ContactsFlashList = ({data}: any) => {
  const stickyHeaderIndices = data
    .map((item: any, index: number) => {
      if (typeof item === 'string') {
        return index;
      } else {
        return null;
      }
    })
    .filter((item: any) => item !== null) as number[];

  return (
    <FlashList
      showsVerticalScrollIndicator={false}
      estimatedItemSize={44}
      data={data}
      renderItem={({item}) => {
        if (typeof item === 'string') {
          return <ContactSectionHeader title={item} />;
        } else {
          return <ContactCell contact={item} />;
        }
      }}
      getItemType={item => {
        return typeof item === 'string' ? 'sectionHeader' : 'row';
      }}
      ItemSeparatorComponent={ContactDivider}
      stickyHeaderIndices={stickyHeaderIndices}
      ListHeaderComponent={ContactHeader}
    />
  );
};

export default ContactsFlashList;
```

For greater visibility, I have attached a video:
https://user-images.githubusercontent.com/43568935/231815334-b99d935f-c0d2-4bc7-9756-fd92123dde17.mp4

**Comment by KolissnikBogdan** [comment]
Sorry, it was my mistake)

**Comment by GNUGradyn** [comment]
What was the issue? I'm running into the same thing
