### ISSUE TITLE
Load time => blank

### ISSUE THREAD

**Issue by pierroo** [Shopify/flash-list#830]
## Current behavior
The doc mentions a Load Time, "tracking elapsed time from the point the list was created to the time when it's children are visible to the user"
=> Unfortunately this load time leads to a brutal "blink" that can take up to one second if the load time is 1sec.
And even if it were just 200ms, the blink still happens and makes the skeleton essentially useless since there is that "in between state" where nothing is displayed.
(isLoaded is from the state, waiting for an async data fetching)

```
 {
          isLoaded ? (
            <FlashList
              ref={scrollRef}
              data={list}
              renderItem={renderItem}
              keyExtractor={(e) => e._id}
              ListHeaderComponent={<Header />}
            />
          ) :  (
            <Skeleton />
          )
        }
```

## Expected behavior

Any way to force the display of a specific component during that "load time"?

## Platform:

- [ x] iOS
- [x ] Android

## Environment

1.4.0

**Comment by saadi-ninjasCode** [comment]
I fixed the same issue with two props: 

1. estimatedItemSize
2. estimatedListSize

Also, I have skeleton loading same as you. Hopefully this props will help you,
