### ISSUE TITLE
Inconsistent Recycling behaviour when having `estimatedListSize`

### ISSUE THREAD

**Issue by mk-nickyang** [Shopify/flash-list#835]
## Current behavior

When having `useState` in the item component and it gets out of the viewport, item can get recycled, state can transfer to another component. This is expected and well-documented [here](https://shopify.github.io/flash-list/docs/recycling).

_Example: Press the button will update the item state, changing the item height and background color. Try pressing the button in the last item and scrolling up, you can see some other items have different height and background color too._

https://user-images.githubusercontent.com/29244509/235815294-f01f1790-602d-4c04-8e66-6b3c9377fcfe.MP4

Expo Snack: https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-1

---

However, when `estimatedListSize` is added, looks like items stop getting recycled. See below

https://user-images.githubusercontent.com/29244509/235816164-0dcb6674-0430-498f-a53f-97a4def4090d.MP4

Expo Snack: https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-2

---

Then I tried loading more items after 3 seconds (to mimic infinite scroll), items are getting  recycled again. See below

https://user-images.githubusercontent.com/29244509/235816644-67a5e87f-8068-4985-83f1-fcac02d5c9a5.mp4

Expo Snack: https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-3

---

Just wondering is this expected? And is FlashList recycling supposed to behave differently when having `estimatedListSize`?

## Expected behavior

If the above is expected, probably a good idea to document how `estimatedListSize` affects recycling;
If the above is NOT expected, then Recycling should work in a more consistent way

## To Reproduce

Pressing the button in the last item and then scrolling up, compare the Recycling behaviour among these 3 Expo Snacks

- Expected Recycling behaviour: https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-1
- No Recycling after `estimatedListSize` is added: https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-2
- Recycling is back after loading more items: https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-3

## Platform:

- [x] iOS
- [x] Android

## Environment

The Expo example is using `1.3.1`, but tested with the latest version `1.4.3` locally too, can still reproduce

**Comment by L0rdCr1s** [comment]
did you find the solution, i'm facing the same problem, some data from the previous item still shows after the component is recycled. I'm using redux in my case.

**Comment by mk-nickyang** [comment]
@L0rdCr1s You can reset state when a new item is rendered, see the example here
https://shopify.github.io/flash-list/docs/recycling/

As I mentioned above, recycling itself is expected and well-documented. This issue is more about knowing how `estimatedListSize` works with recycling.

**Comment by ameer-taghavi** [comment]
> @L0rdCr1s You can reset state when a new item is rendered, see the example here https://shopify.github.io/flash-list/docs/recycling/
> 
> As I mentioned above, recycling itself is expected and well-documented. This issue is more about trying to figure out how `estimatedListSize` works with recycling.

What's the best value for `estimatedListSize.height` when i have list with pagination(lazy loading with load more)?

**Comment by mk-nickyang** [comment]
I just realised I have the wrong `estimatedListSize` set, it should be the visible height and width of the list (or the list container size), instead of the scroll content size (see [here](https://shopify.github.io/flash-list/docs/usage#estimatedlistsize)).

After updating the `estimatedListSize` to the list container size (window width and height) in [demo 2](https://snack.expo.dev/@lucissa/flashlist-recycle-playground---demo-2), recycling works again as expected.

Will close this issue now, sorry for the drama.
