### ISSUE TITLE
Pressed item with flashlist not working

### ISSUE THREAD

**Issue by dngns** [Shopify/flash-list#846]
## Current behavior

https://github.com/Shopify/flash-list/assets/80993895/89359a29-4362-4a46-8a61-daec7b5d300a

## Expected behavior

https://github.com/Shopify/flash-list/assets/80993895/8f64f5e0-b923-4863-b47a-211c459ec541

## To Reproduce

I have 2 components, First is **ItemSelected** has prop **isActive** and using memo for it checks if the isActive prop of the previous and next props is the same. If it is, the component is not re-rendered.
In second component is **ListSelected** has this code for render list.
![image](https://github.com/Shopify/flash-list/assets/80993895/fd3d17af-0ad2-4ca3-88ad-1dd058646f33)

## Platform:

- [x] iOS
- [x] Android

## Environment

 shopify/flash-list : "^1.4.3"
 react-native: "0.71.7",

```[tasklist]
### Tasks
```

**Comment by ducnguyen4301** [comment]
> Flashlist does not update itself if data or key is not updated. You can combine data and arraySelected in a single array or you can use extraData prop to pass selected ids to your list. Here is an example [snack](https://snack.expo.dev/@suleymanbariseser/selectable-flashlist-item)

thanks for it 🔥
