### ISSUE TITLE
FlashList is not rendering correct item data. It is mixing/reusing/shuffling components/images.

### ISSUE THREAD

**Issue by VictorioMolina** [Shopify/flash-list#855]
## Current behavior

I have a memoized Card component which is quite complex and consumes React.Context to consume dynamic data like `isLiked`, `totalComments`, ...

For some reasons, FlashList renders same components again and again, not the correct items data.

This is my Card component:

```javascript
export default function RootCard({
  data,
  cached = false,
  withFade = true,
  onPressOptions,
  onLayout,
}) {
  useLanguage();

  const lastData = useRef(data);

  if (data.id !== lastData.current.id) {
    console.log(`Real: ${data.id}, Fake: ${lastData.current.id}`);
  }

  return (
    <Card
      data={{
        ...data,
        date: getReadableTimeSince(data.date),
      }}
      cached={cached}
      withFade={withFade}
      onPressOptions={onPressOptions}
      onLayout={onLayout}
    />
  );
}

RootCard.propTypes = ContentCardPropTypes;

const Card = memo(
  ({
    data,
    cached,
    withFade,
    onPressOptions,
    onLayout,
  }) => {
    const updatedCardData = useUpdatedCardData(data); // get the most up-to-date data from Context API

    return (
      <MemoizedCard
        data={updatedCardData}
        cached={cached}
        withFade={withFade}
        onPressOptions={onPressOptions}
        onLayout={onLayout}
      />
    );
  },
  areContentCardPropsEqual
);

Card.propTypes = RootCard.propTypes;

const MemoizedCard = memo(
  ({
    data,
    cached,
    withFade,
    onPressOptions,
    onLayout,
  }) => {
    const { colors } = useTheme();

    const {
      id,
      userData,
      images,
      dimensions,
      nsfw,
      location,
      text,
      description,
      totalViews,
      totalLikes,
      totalComments,
      isLiked,
      date,
    } = data;

    const contentType = VALID_MAIN_CONTENT_TYPES[images ? 0 : 1];

    /**
     * Handle press events on the options button.
     *
     * @returns {void} Nothing.
     */
    const handleOnPressOptions = () => {
      //
      // Note: We are passing the most up-to-date version of
      // the data object, not the original one.
      //
      onPressOptions?.(data);
    };

    const optionsButtonPressHandler = onPressOptions
      ? handleOnPressOptions
      : undefined;

    return (
      <View
        onLayout={onLayout}
        style={[
          globalStyles.flexContainer,
          { backgroundColor: colors.white },
        ]}
      >
        <AuthorRow
          userData={userData}
          date={date}
          onOptionsButtonPress={optionsButtonPressHandler}
        />

        {!!description && <Description text={description} />}

        {images
          ? (
              <PostContent
                images={images}
                dimensions={dimensions}
                location={location}
                cached={cached}
                nsfw={nsfw}
                withFade={withFade}
              />
            )
          : (
              <ThreadContent text={text} />
            )
        }

        <SocialRow
          contentType={contentType}
          contentId={id}
          contentOwnerId={userData.id}
          totalViews={totalViews}
          totalLikes={totalLikes}
          totalComments={totalComments}
          isLiked={isLiked}
          date={date}
        />
      </View>
    );
  },
  areMemoizedContentCardPropsEqual
);

MemoizedCard.propTypes = Card.propTypes;
```

And here my memo arePropsEqual functions:

```javascript
export function areContentCardPropsEqual(prevProps, nextProps) {
  return (
    prevProps.data.date === nextProps.data.date &&
    prevProps.onPressOptions === nextProps.onPressOptions
  );
}

export function areMemoizedContentCardPropsEqual(prevProps, nextProps) {
  const {
    data: {
      description: prevDescription,
      totalViews: prevTotalViews,
      totalLikes: prevTotalLikes,
      totalComments: prevTotalComments,
      date: prevDate,
    },
    onPressOptions: prevOnPressOptions,
  } = prevProps;

  const {
    data: {
      description: nextDescription,
      totalViews: nextTotalViews,
      totalLikes: nextTotalLikes,
      totalComments: nextTotalComments,
      date: nextDate,
    },
    onPressOptions: nextOnPressOptions,
  } = nextProps;

  return (
    prevDate === nextDate &&
    prevDescription === nextDescription &&
    prevTotalViews === nextTotalViews &&
    prevTotalLikes === nextTotalLikes &&
    prevTotalComments === nextTotalComments &&
    prevOnPressOptions === nextOnPressOptions
  );
}
```

## Expected behavior

I am transitioning from FlatList to FlashList. With FlatList, everything worked good but with performance issues. How do we make FlashList to render the correct data for each component in the list?

## Platform:

- [ x ] iOS
- [ x ] Android

## Environment

1.3.1

**Comment by VictorioMolina** [comment]
Also, notice that all children (SocialRow, AuthorRow, ...) are memoized too.

**Comment by VictorioMolina** [comment]
It was my mistake. Sorry, I was new with the recycling concept.

**Comment by salesp07** [comment]
@VictorioMolina I recently ran into this issue and had to turn back to FlatList. Should this issue really be closed?

**Comment by Lychas** [comment]
Hello here in 2024, any idea how to solve it while still using flashlist?

**Comment by vanacoree** [comment]
> Hello here in 2024, any idea how to solve it while still using flashlist?
> 
> Here is my code:
> 
> ### ListPost.tsx
> ```
> import { StyleSheet, Text, View } from "react-native";
> import React, { useState, useEffect } from "react";
> 
> import { FlashList } from "@shopify/flash-list";
> import ItemBox from "../item/PostItem";
> 
> import toast from "@/functions/toast";
> 
> import makePostRequest, { makeRequestInput } from "@/functions/makePostRequest";
> 
> import { Settings } from "@/AppContext";
> 
> import { StackNavigationProp } from "@react-navigation/stack";
> import { HomeStackParams } from "@/types/navigation";
> 
> import type { Post } from "@/types/graphql";
> 
> type navigationType =
>     | StackNavigationProp<HomeStackParams, "PostsListPage">
>     | StackNavigationProp<HomeStackParams, "HomePage">;
> 
> type ListPostsItems = Post[];
> 
> const ListPosts = ({
>     requestApiInfo: requestData,
>     navigation,
>     header,
>     footer,
> }: {
>     requestApiInfo: makeRequestInput;
>     navigation: navigationType;
>     header?: React.JSX.Element;
>     footer?: React.JSX.Element;
> }) => {
>     const [posts, setPosts] = useState<ListPostsItems>([]);
>     const [nextToken, setNextToken] = useState<string>("");
>     const [loading, setLoading] = useState(false);
> 
>     const settings = React.useContext(Settings);
> 
>     const fetchPosts = async () => {
>         if (loading) return;
>         if (posts) setPosts([]);
>         setLoading(true);
>         let response = await makePostRequest(requestData);
>         if (response === false) {
>             toast("Error fetching posts");
>             setLoading(false);
>             return;
>         }
>         setNextToken(response.nextToken);
>         setPosts(response.items);
>         setLoading(false);
>     };
> 
>     useEffect(() => {
>         fetchPosts();
>     }, []);
> 
>     async function loadMore() {
>         if (loading) return;
>         if (!nextToken) return;
>         setLoading(true);
>         let response = await makePostRequest({ ...requestData, body: { nextToken: nextToken } });
>         if (response === false) {
>             toast("Error fetching posts");
>             setLoading(false);
>             return;
>         }
>         setNextToken(response.nextToken);
>         setPosts([...posts, ...response.items]);
>         setLoading(false);
>     }
> 
>     return (
>         <View
>             style={{
>                 flex: 1,
>                 height: "100%",
>                 width: "100%",
>                 backgroundColor: settings.colorTheme.primaryColor,
>             }}
>         >
>             <FlashList
>                 data={posts}
>                 renderItem={(post) => <ItemBox post={post.item} navigation={navigation} />}
>                 estimatedItemSize={240}
>                 refreshing={loading}
>                 onRefresh={fetchPosts}
>                 onEndReachedThreshold={0.5}
>                 onEndReached={loadMore}
>                 keyExtractor={(item) => item.id}
>                 ListHeaderComponent={header}
>                 ListFooterComponent={footer}
>             />
>         </View>
>     );
> };
> 
> export default ListPosts;
> ```
> 
> PostItem.tsx (ItemBox*)
> 
> ```
> import { StyleSheet, Text, View, Pressable } from "react-native";
> import React, { useState, useEffect } from "react";
> 
> import { Image } from "expo-image";
> import ReactNativeImage from "@/classes/Image";
> 
> import { SharedElement } from "react-navigation-shared-element";
> 
> import toast from "@/functions/toast";
> import formatNumber from "@/functions/formatNumber";
> 
> import { Settings } from "@/AppContext";
> 
> import { StackNavigationProp } from "@react-navigation/stack";
> import { HomeStackParams } from "@/types/navigation";
> import type { Post, Photo } from "@/types/graphql";
> 
> type componentProps = {
>     navigation:
>         | StackNavigationProp<HomeStackParams, "PostsListPage">
>         | StackNavigationProp<HomeStackParams, "HomePage">;
>     post: Post;
> };
> 
> //TODO: Add Boosted tag
> const PostItem = ({ navigation, post }: componentProps) => {
>     const [imageUrl, setImageUrl] = useState<string | undefined>(undefined);
> 
>     const settings = React.useContext(Settings);
> 
>     const styles = StyleSheet.create({
>         view: {
>             width: "94%",
>             // aspectRatio: 17 / 13,
>             marginLeft: "auto",
>             marginRight: "auto",
>             borderRadius: 10,
>             alignItems: "center",
>             position: "relative",
>             zIndex: 10,
>             backgroundColor: settings.colorTheme.customFive,
>         },
> 
>         image: {
>             width: "100%",
>             height: "100%",
>             alignSelf: "center",
>             position: "relative",
>             backgroundColor: "gray",
>             borderRadius: 10,
>         },
>         info: {
>             width: "90%",
>             flexDirection: "column",
>             marginVertical: 4,
>         },
>         secondInfo: {
>             flexDirection: "row",
>             justifyContent: "space-between",
>             marginBottom: 7,
>         },
>         text: {
>             fontSize: settings.font.fontSize[16],
>             fontFamily: settings.font.fontFamily,
>             fontWeight: "600",
>         },
>         header: {
>             width: "100%",
>             flexDirection: "row",
>             justifyContent: "space-between",
>             alignItems: "center",
>             fontSize: settings.font.fontSize[20],
>             textAlign: "center",
>         },
>     });
> 
>     function showPost() {
>         navigation.navigate("ItemPage", { post: post, mainImageUri: imageUrl });
>     }
> 
>     function getArea() {
>         if (post.totalArea) {
>             return formatNumber(post.totalArea) + " M²";
>         }
>         return "Hidden";
>     }
> 
>     function getPrice() {
>         if (post.price && post.currency) {
>             return formatNumber(post.price) + " " + post.currency;
>         }
>         return "Hidden";
>     }
> 
>     function getNumberOfRooms() {
>         if (post.numberOfTotalRooms) {
>             return post.numberOfTotalRooms + " Rooms";
>         }
>         return "No Rooms";
>     }
> 
>     async function fetchImage({ name, identityId }: Photo) {
>         try {
>             let image = await new ReactNativeImage({}).getFromS3({
>                 imageKey: name,
>                 identityId: identityId,
>             });
>             setImageUrl(image);
>         } catch {
>             toast("Error getting the main image");
>         }
>     }
>     useEffect(() => {
>         fetchImage(post.mainImage);
>     }, []);
>     return (
>         <Pressable onPress={() => showPost()} style={{ marginBottom: 30, marginTop: 2 }}>
>             <View style={styles.view}>
>                 <View
>                     style={{
>                         width: "98%",
>                         aspectRatio: 16 / 9,
>                         justifyContent: "center",
>                         marginVertical: 8,
>                         borderRadius: 10,
>                         backgroundColor: "gray",
>                     }}
>                 >
>                     {imageUrl ? (
>                         <SharedElement id={imageUrl}>
>                             <Image
>                                 style={styles.image}
>                                 source={{ uri: imageUrl }}
>                                 contentFit="cover"
>                                 recyclingKey={post.id}
>                             />
>                         </SharedElement>
>                     ) : null}
>                 </View>
>                 <View style={styles.info}>
>                     <Text style={[styles.text, styles.header]}>{post.title}</Text>
>                     <View style={styles.secondInfo}>
>                         <Text style={styles.text}>{getPrice()}</Text>
>                         <Text style={styles.text}>{getArea()}</Text>
>                         <Text style={styles.text}>{getNumberOfRooms()}</Text>
>                     </View>
>                     <Text style={styles.text}>
>                         {post.address[`name_${settings.language.code}`]}
>                     </Text>
>                     {post.address.nearby && <Text style={styles.text}>{post.address.nearby}</Text>}
>                 </View>
>             </View>
>         </Pressable>
>     );
> };
> 
> export default PostItem;
> ```

for me the error was in the <FlashList with the renderItem function. I resolved it by passing the following renderItem function to the FlashList renderItem:

Important is that in the renderItem function the View that is the parent needs the key={index} -> this resolved it for me 

 ```
 const renderItem = useCallback(({ item, index }) => {
        return (
            <View key={index} style={{
                backgroundColor: "black", width: Dimensions.get("window").width, height: feedItemHeight
            }}>
                <PostSingle item={item} isActive={activeVideoIndex === index} onRefresh={onRefresh} index={index} />
            </View >
        )
    }, [activeVideoIndex])
```
and my <FlashList looks like: 

```
<FlashList
       renderItem={renderItem}
... />
```

**Comment by Lychas** [comment]
3 weeks later I have fully given up and now using a flatlist, seems like there is no fix to this issue 🥲

**Comment by bpoulaindev** [comment]
> > Important is that in the renderItem function the View that is the parent needs the key={index} -> this resolved it for me
> 
> That does solve it but sadly it goes against the rules of using a flash list as it stated in their docs:
> 
> > Remove key prop
> > WARNING
> > Using key prop inside your item and item's nested components will highly degrade performance.
> > Make sure your item components and their nested components don't have a key prop. Using this prop will lead to FlashList not being able to recycle views, losing all the benefits of using it over FlatList.

Same here, i'm just rendering a 30 element list to make a dynamic search component, i had elements being visually correct but triggering the wrong fucntion, the only solution was to add a key in the rendered child

**Comment by UsamaUthman** [comment]
```
const lastItemId : String = useRef(postId);
const [imageUrl, setImageUrl] = useState<string | undefined>(undefined);

if (lastItemId.current !== post.postId) {
    lastItemId.current = postId;
    setImageUrl(post.image)
    //setComment(post.comment)
   //setLikeCount(post.like)
   ..................
  }
```
  i think this will fix your issue , just follow docs here : https://shopify.github.io/flash-list/docs/recycling

**Comment by wjbright** [comment]
The FlashList [docs](https://shopify.github.io/flash-list/docs/fundamentals/performant-components#leaf-components) don't say much about memoizing the renderItem component (only sibling components that don't rely on the item). This was the issue in my case. 

Removing the `React.memo` on the parent component returned from the `renderItem` fixes the issue without violating the `key` prop constraint of the renderItem component. If you need to make the component more performant, you might want to focus on 'memoizing' the details of the component.

**Comment by angelopedroso** [comment]
> The FlashList [docs](https://shopify.github.io/flash-list/docs/fundamentals/performant-components#leaf-components) don't say much about memoizing the renderItem component (only sibling components that don't rely on the item). This was the issue in my case.
> 
> Removing the `React.memo` on the parent component returned from the `renderItem` fixes the issue without violating the `key` prop constraint of the renderItem component. If you need to make the component more performant, you might want to focus on 'memoizing' the details of the component.

That's it, memo was the problem. But do you know a way to use memo without occur it?
