### ISSUE TITLE
Flashlist on expo web re-renders

### ISSUE THREAD

**Issue by devoren** [Shopify/flash-list#870]
## Current behavior
I have an expo app that uses expo router and bottom tabs. When I switch between web tabs (on unmount), the height of the flashlist is 0. So i get a warning:
```
FlashList's rendered size is not usable. Either the height or width is too small (<2px). 
Please make sure that the parent view of the list has a valid size. 
FlashList will match the size of the parent.
```

https://github.com/Shopify/flash-list/assets/99968085/6020adf7-7206-400e-a4ca-f54ca0417e6a

## Expected behavior
When I switch between web tabs I think flashlist should not be unmounted

## To Reproduce
1. Create an expo web app
2. Use Tabs as expo router layout
3. Add flashlist component
4. Switch between tabs

## Platform:

- [ ] iOS
- [ ] Android
- [x] Web

## Environment

1.4.3

**Comment by nandorojo** [comment]
Yeah I'm actually getting the same thing here. I think the re-rendering is a bit of a red herring though. FlashList is just completely off when measuring its parent or something.

**Comment by devoren** [comment]
@nandorojo maybe, but I just switched to a flat list on the web for a while

**Comment by naqvitalha** [comment]
We don't really control if tabs unmount the list. The warning has been improved and will not show during active resizing. Upgrade to v1.6.4.

**Comment by bhyoo99** [comment]
@naqvitalha still same issue after 1.6.4
Please re-open this issue.


**when isMouned**
<img width="958" alt="스크린샷 2024-06-21 오후 10 16 07" src="https://github.com/Shopify/flash-list/assets/62757768/81904429-3d2a-4003-8e73-cf00fda40eb6">

**when unMouned (move to 2nd tab)**
<img width="960" alt="스크린샷 2024-06-21 오후 10 18 03" src="https://github.com/Shopify/flash-list/assets/62757768/3c3f9475-a24a-4377-8a22-7911de3e73da">

**Comment by huult** [comment]
Do we have a solution for that?
