### ISSUE TITLE
column span of the item is incorrect

### ISSUE THREAD

**Issue by NemoDream** [Shopify/flash-list#874]
## Current behavior

When overrideItemLayout is used to change the column span, the column span of the item is different, and the device screen direction is switched, the column span of the item is incorrect.
https://snack.expo.dev/@nemo0625/flashlist-screen-orientation-switch-bug

https://github.com/Shopify/flash-list/assets/21306508/874a671b-e8df-4064-ba74-087a13564524

## Expected behavior

the column span of the item is normal.
![截图](https://github.com/Shopify/flash-list/assets/21306508/401a31a5-cd2b-435c-a9b2-fb3bf96c2176)

## To Reproduce

Just switch screen direction.

## Platform:

- [ ] iOS
- [ ] Android

## Environment

@shopify/flash-list 1.4.3

**Comment by adesugbaa** [comment]
I have the same issue - glitchy performance when numColumns > 1, and device rotated or window resized. 1st row typically has 2nd column missing, other times 2nd column overlaps 1st column.

Completely unusable.

**Comment by naqvitalha** [comment]
In case of orientation changes it's important to ensure that component updates. Also, clearing the layout cache will help.  Use the following code:

```js
  const {height, width} = useWindowDimensions()
  useLayoutEffect(() => {
      flashListRef.current?.clearLayoutCacheOnUpdate();
  },[height > width])
  ```

**Comment by seva3l** [comment]
this issue still exist. The workaround is to add key on the Flashlist and as well as using the clearLayoutCacheOnUpdate
