### ISSUE TITLE
marginBottom value in style is ignored

### ISSUE THREAD

**Issue by murat-mehmet** [Shopify/flash-list#882]
## Current behavior

`marginBottom` value in style property is not getting rendered. 
Current workaround is wrapping FlashList into a view and applying `marginBottom` to the view.

## Expected behavior

`marginBottom` is working fine with FlatList so I think it should also be implemented in FlashList too.

## To Reproduce

<FlashList style={{marginBottom: 100}} />

## Platform:

- [ ] iOS
- [X] Android

## Environment

1.5.0

**Comment by naqvitalha** [comment]
This is expected. We only support limited styles
