### ISSUE TITLE
TypeScript error with FlashListProps

### ISSUE THREAD

**Issue by TNAJanssen** [Shopify/flash-list#887]
## Current behavior

Gives an TypeScript error:
TS2430: Interface  FlashListProps<TItem>  incorrectly extends interface  ScrollViewProps 
Types of property  contentContainerStyle  are incompatible.
Type  ContentStyle | undefined  is not assignable to type  StyleProp<ViewStyle> 
Type  ContentStyle  is not assignable to type  StyleProp<ViewStyle> 
Type  ContentStyle  is not assignable to type  ViewStyle 
Types of property  padding  are incompatible.
Type  string | number | undefined  is not assignable to type  DimensionValue | undefined 
Type  string  is not assignable to type  DimensionValue | undefined 

## Expected behavior

Should not give an error

## To Reproduce

Install and run TypeScript check

## Platform:

- [X] iOS
- [X] Android

## Environment

1.5.0

**Comment by eightyfive** [comment]
I get another TS error when passing an array to `contentContainerStyle`:

```
Type 'ViewStyle[]' is not assignable to type 'ContentStyle | AnimatedNode<ContentStyle | undefined> | undefined'.
```

**Comment by uhrohraggy** [comment]
Can you release a patch for this? 

It's mostly a simple update from 

```
export interface ContentStyle {
  backgroundColor?: ColorValue;
  paddingTop?: string | number;
  paddingLeft?: string | number;
  paddingRight?: string | number;
  paddingBottom?: string | number;
  padding?: string | number;
  paddingVertical?: string | number;
  paddingHorizontal?: string | number;
}
```

to

```
import {
   ...
  DimensionValue,
} from "react-native";
...
export interface ContentStyle {
  backgroundColor?: ColorValue;
  paddingTop?: DimensionValue;
  paddingLeft?: DimensionValue;
  paddingRight?: DimensionValue;
  paddingBottom?: DimensionValue;
  padding?: DimensionValue;
  paddingVertical?: DimensionValue;
  paddingHorizontal?: DimensionValue;
}
```

React Native version is "0.72.4"
