### ISSUE TITLE
Flashlist caches scrolling carousels from previous cells

### ISSUE THREAD

**Issue by ClemCornet** [Shopify/flash-list#891]
## Current behavior

I have a list with cells containing photo carousels. Each time a new batch of items is loaded, the cell keep in cache the scroll of the previous item.

## Expected behavior

Is there a way to prevent this cell memoization behavior? 

## To Reproduce

Create a flashlist with a simple vertical carousel photo inside rows

## Platform:

- [x] iOS
- [x] Android

## Environment

```
"@shopify/flash-list": "1.4.0"
"react-native": "0.71.8"
"expo": "~48.0.18"
```

**Comment by ahmetares** [comment]
Using `react-native-fast-image` solved this problem on images for me

**Comment by ClemCornet** [comment]
@ahmetares Thank you for your reply. Even using react-native-fast-image (expo-image for me), I still have the same problem, it keep the scroll of previous cards >


https://github.com/Shopify/flash-list/assets/32069074/e597423c-a66a-4e60-8365-3381bedb4ada

I don't know if it's possible to bypass the library's behavior 🤔

**Comment by yaminyassin** [comment]
can you add a expo snack with reproducible code this might be a key problem.

**Comment by tanlucvo** [comment]
Yupp!! Assume is when Item1 out of screen and Item10 move into screnn, Flashlist will recycle Item1 by data of Item10, and keep current state of Item1, then cause issue above. Solution is reset carousel index when data change example 
```
useEffect(() => {
  // Reset carousel position (view was recycled for another item),method move to index inside carousel. 
  carouselRef.current.moveToIndex(0);
}, [item.id]);
```

**Comment by neaRRRRR** [comment]
Giving **key** for Carousel component solved the issue for me

**Comment by jspizziri** [comment]
@ClemCornet I actually think this should be reopened as it seems like something that would ideally be handled in `FlashList`. AFAIK, using a `key` isn't ideal as that is against the recommendations of flashlist as it causes another render and reduces performance.

Here's the homebrewed solution that I came up with:

```tsx
// OuterList is a vertically scrolling list which. Each item will be a horizontally scrolling nested list
const OuterList = () => {
  // ...
  const scrollMap = useRef<Record<string, number | undefined>>({});
  
  return (
    <FlashList
      data={items}
      extraData={scrollMap.current}
      renderItem={(props) => (
        <InnerList
          item={props.item}
          scrollMap={props.extraData}
        />
      )}
    />
  )
}

// The nested, horizontally scrolling list. Recieves the `scrollMap`, updates it, and scrolls appropriately
const InnerList = ({
  item,
  scrollMap,
}: { 
  item: any;
  scrollMap: Record<string, number | undefined>;
}) => {
  // ...
  const flatListRef = useRef<FlashList<CollectionItem> | null>();
  const lastItem = useRef(item);

  // FlashList recycles components but it doesn't properly update their scroll
  // position. So we reset the scroll position here to the last known position
  if (item.id && lastItem.current.id !== item.id) {
    lastItem.current = item.id;
    const position = scrollMap[item.id] || 0;

    console.log(">>>>>>> scrolling to offset", item.id, position);
    flatListRef.current?.scrollToOffset({ offset: position, animated: false });
  }

  return (
    <FlashList
      ref={r => flatListRef.current = r}
      horizontal
      data={item.someData}
      extraData={scrollMap.current}
      renderItem={() => {
        // Item to render
      }}
      // NOTE: we need to track the scroll position
      onScroll={({ nativeEvent: { contentOffset: { x }}}) => {
        scrollMap[item.id] = x;
      }}
    />
  )
}
```

Anyways, this seems to be working for now. It'd be great if FlashList could take care of this internally somehow.

**Comment by alyosha** [comment]
+1 to reopen 🙏

**Comment by naqvitalha** [comment]
While we can automatically scroll to offset 0 internally, it may not be the best idea. In a lot of cases people generate new data array across renders and there's no reliable way to predict that the list has been recycled inside a parent list or due to some manipulation by the dev. My suggestion is to just scroll to 0 when the data array changes and make sure data is memoized correctly.
