### ISSUE TITLE
Rendering issue on android (React Native Fabric Arch)

### ISSUE THREAD

**Issue by mrshahzeb7** [Shopify/flash-list#901]
## Current behavior
FlashList item is flickering on android and hiding/appearing on scroll on android platform video attached, It is the example provided in fixture, not my code

## Expected behavior
Should run smoothly and without any visibility issue

## To Reproduce
I am just running fixture examples on android app with Fabric arch enabled!

## Platform:

- [x] Android

https://github.com/Shopify/flash-list/assets/69900372/2cc6cc63-ce8b-4259-9b14-d2a9839b830d

## Environment

    "@shopify/flash-list": "^1.5.0",

**Comment by devoren** [comment]
https://github.com/Shopify/flash-list/pull/550
