### ISSUE TITLE
Adding item to beginning of list crashes FlashList

### ISSUE THREAD

**Issue by myou11** [Shopify/flash-list#925]
## Current behavior

When I add items to the end of my list, everything works fine, but when I specifically add an item above the first item (i.e. to the beginning of the list), it crashes the app due to the following error: `Cannot read property 'x' of undefined' in RecyclerListView's LayoutManager `WrapGridLayoutManager.prototype._locateFirstNeighbourIndex`.
I found the [following issue from the recyclerlistview library](https://github.com/Flipkart/recyclerlistview/issues/234). The issue the reporter had here is the same issue I am having now with this FlashList library. I cant apply the fix they did since they changed the way they specified their dataprovider prop. This library has an API more in line with the native FlatList, so I am just providing my data as a simple array. Im not sure if the bug I'm having needs to be resolved in recyclerlistview or this library.

Is there a way to get the `this._layouts` size in sync with the `startIndex`?

<img width="947" alt="Screen Shot 2023-09-27 at 4 52 55 PM" src="https://github.com/Shopify/flash-list/assets/16094260/a807360a-c5fe-419b-b11c-ffafcc2005ff">

https://github.com/Shopify/flash-list/assets/16094260/97ddd595-042e-4b69-9fa8-971e1fb97201

## Expected behavior

You should be able to insert an item to the beginning of your list and the app should not crash

## To Reproduce

https://github.com/myou11/RealmTaskAppTest/tree/flashlist

- press "Create Store" button
- press "Create Task" button however many times
- press "Add Subtask Above" button within the first task
- app will crash, but it may not log the error all the time (please refer to the above for the error)

## Platform:

- [x] iOS
- [ ] Android

## Environment

1.6.1

**Comment by vagnerlandio** [comment]
I'm gettings a similar error even with an empty list -> `TypeError: Cannot read property '__extends' of undefined`

**Comment by nickprihodko** [comment]
Same error
![image](https://github.com/Shopify/flash-list/assets/11626849/ec189f4d-13f3-476a-b237-a26be2c9206e)

**Comment by 0oTMNo0** [comment]
I have the same problem in my chat list when I scroll so fast this error shows up

I solved it by changing node modules to:

..\done-mobile\node_modules\recyclerlistview\dist\reactnative\core\layoutmanager.js

before ===> 
    line 192: else if (this._layouts[i].x === 0)
after ===>
    line 192: else if (this._layouts[i]?.x === 0)
    
    @ho3ein-boka

**Comment by pauloalozen** [comment]
I was experiencing the same issue. In my case, it was happening because of state mutation, as @naqvitalha mentioned earlier. What I did to solve the problem was to add a condition to only display the flashlist after the state had the initial data, like this: state.length > 0.
