### ISSUE TITLE
onEndReached called on initial render 

### ISSUE THREAD

**Issue by Samide47** [Shopify/flash-list#937]
## Current behavior

<FlashList
      data={products}
      keyExtractor={(item) => item._id}
      estimatedItemSize={200}
      numColumns={2}
      showsVerticalScrollIndicator={false}
      renderItem={(item) => (
        <SingleProduct
          key={item.item._id}
          navigation={navigation}
          product={item.item}
        />
      )}
      ListEmptyComponent={<EmptyProducts navigation={navigation} />}
      onEndReached={() => {
        console.log("on end reach");
        handleStartLoadingMore() && loadMore();
      }}
      onEndReachedThreshold={0.25}
      ListFooterComponent={isLoading && <Text>loading more...</Text>}
    />

 

 

## Platform:

- [ x] iOS
- [ x] Android

## Environment

"@shopify/flash-list": "^1.6.2",
"react": "18.2.0", 
"react-native": "0.72.5",

**Comment by jianxinzhoutiti** [comment]
+1

**Comment by zavbala** [comment]
Yeah, run twice

**Comment by LabLamb** [comment]
Mine ran non-stop

**Comment by naqvitalha** [comment]
If the content doesn't fill the screen on initial render then the callback will fire. If it's being called incorrectly then most like the `estimatedItemSize` value is incorrect.

**Comment by purplereborn** [comment]
```
const [onEnd, setOnEnd] = useState<boolean>(true);

onMomentumScrollBegin={() => setOnEnd(false)}
onEndReached={() => {
          if (!onEnd) {
            onEndReached();
          }
 }}
```

**Comment by natemartins** [comment]
> Following the guidelines on estimatedItemSize helped. I had initially thought it meant how many items would be displayed on each render, but fixing it appropriately solved the problem.
> 
> > If the content doesn't fill the screen on initial render then the callback will fire. If it's being called incorrectly then most like the `estimatedItemSize` value is incorrect.

@jothamc Could you explain further what exactly helped you? Thanks

**Comment by jothamc** [comment]
> > Following the guidelines on estimatedItemSize helped. I had initially thought it meant how many items would be displayed on each render, but fixing it appropriately solved the problem.
> > > If the content doesn't fill the screen on initial render then the callback will fire. If it's being called incorrectly then most like the `estimatedItemSize` value is incorrect.
> 
> [@jothamc](https://github.com/jothamc) Could you explain further what exactly helped you? Thanks

I had thought that `estimatedItemSize` was the amount of items in a list (I'm not sure why I thought that, maybe the name of the prop), but [when I read properly](https://shopify.github.io/flash-list/docs/estimated-item-size/) that it's meant to be the value of the height of one item, it helped me calculate the right value for my app.

**Comment by LovesWorking** [comment]
The issue happens when the parent of the flash list doesn't have a fixed height.

**Comment by deiay** [comment]
onEndReached is running nonstop for me
