### ISSUE TITLE
Build fails for Android compileSdkVersion: 34

### ISSUE THREAD

**Issue by GabrielDierks** [Shopify/flash-list#947]
## Current behavior

Build fails for compileSdkVersion: 34

> Task :shopify_flash-list:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shopify_flash-list:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

## Expected behavior

Build to succeed with compileSdkVersion: 34

## To Reproduce

install a clean build with the mentioned react native and flashlist versions.

## Platform:

- [ ] iOS
- [x] Android

## Environment

    Versions:
    "@shopify/flash-list": "^1.6.2",
    "react-native": "^0.72.5",
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
      Android SDK:
        API Levels: 30, 31, 32, 33, 34
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 34.0.0
        System Images: android-22 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.6.0
      expo-cli: 6.3.7
    Expo Workflow: bare

**Comment by GabrielDierks** [comment]
Also mentioned in #756

**Comment by MattGiertl** [comment]
Happens to me as well while using Expo's EAS build system

**Comment by GabrielDierks** [comment]
As mentioned, fixed by #930
